hazelcast/hazelcast-python-client

hazelcast/core.py, tests/reconnect_test.py
=> Member equals comparison should include both UUID and address

hazelcast/proxy/list.py, hazelcast/proxy/queue.py, hazelcast/proxy/set.py
Listener methods of list,queue and set are refactored for indicating parameters which are functions.
=> Refactor for Listener methods of list,queue and set

hazelcast/proxy/lock.py, hazelcast/proxy/ringbuffer.py, hazelcast/proxy/set.py
ApiDoc added to lock.py , ringbuffer.py and set.py with Python Sphinx format.
add_entry_listener method of set class is refactored for indicating parameters which are functions.
=> ApiDoc for Lock, RingBuffer and Set

hazelcast/proxy/atomic_long.py, hazelcast/proxy/atomic_reference.py, hazelcast/proxy/count_down_latch.py, hazelcast/proxy/semaphore.py
ApiDoc added to atomic_long.py , atomic_reference.py, count_down_latch.py and semaphore.py with Python Sphinx format.
=> ApiDoc for AtomicLong, AtomicReference, CountDownLatch and Semaphore

hazelcast/client.py, hazelcast/core.py, hazelcast/lifecycle.py
ApiDoc added to client.py, core.py and lifecycle.py with Python Sphinx format.
=> ApiDoc for Client, Core and Lifecycle

hazelcast/near_cache.py, hazelcast/partition.py, hazelcast/transaction.py
ApiDoc added to near_cache.py, partition.py and transaction.py with Python Sphinx format.
=> ApiDoc for NearCache, Partition and Transaction

hazelcast/cluster.py, hazelcast/connection.py, hazelcast/future.py
ApiDoc added to cluster.py, connection.py and future.py with Python Sphinx format.
=> ApiDoc for Cluster, Connection and Future

hazelcast/config.py, hazelcast/exception.py, hazelcast/hash.py, hazelcast/serialization/api.py, hazelcast/util.py
ApiDoc added to serialization.api.py, exception.py and util.py with Python Sphinx format.
Existing ApiDoc in hash.py and config.py minorly corrected.
=> ApiDoc for Serialization.Api, Exception, Hash, Util, Config

hazelcast/serialization/data.py
Reformat the apiDoc of serialization.data
=> Reformat the apiDoc of serialization.data

hazelcast/near_cache.py, hazelcast/protocol/codec/map_add_near_cache_entry_listener_codec.py, hazelcast/proxy/map.py, run-tests.sh, start-rc.sh, tests/near_cache_test.py, tests/proxy/hazelcast_test.xml, tests/proxy/map_nearcache_test.py
=> near cache test and invalidation listener fix

hazelcast/protocol/codec/map_put_all_codec.py
=> map_put_all_codec calculate_size fix.

docs/distributed_events.rst, docs/index.rst, hazelcast/__init__.py, setup.py
=> fix version numbers

.gitignore, hazelcast/serialization/api.py, hazelcast/serialization/input.py
This method let create proper buffer size in serializer.
I'm using javaobj-py3 package for Java object unmarshalling.
=> Useful method for custom serializer

hazelcast/serialization/base.py, run-tests.sh, start-rc.sh, tests/serialization/serialization_test.py
=> custom serialization look-up fail for classes with subtype

hazelcast/reactor.py
fixes https://github.com/hazelcast/hazelcast-python-client/issues/58
=> check exception type in asyncore.dispatcher handle_error

hazelcast/connection.py, hazelcast/exception.py, hazelcast/invocation.py, hazelcast/near_cache.py, hazelcast/partition.py, hazelcast/reactor.py, run-tests.sh, start-rc.sh, tests/shutdown_test.py
=> Client hangs on member shutdown

hazelcast/cluster.py, hazelcast/config.py, tests/reconnect_test.py
=> Use last known memberlist when reconnecting to cluster

hazelcast/cluster.py, tests/reconnect_test.py
fixes https://github.com/hazelcast/hazelcast-python-client/issues/70
=> All addresses are tried on each connect attempt

examples/main.py
=> Import of hazelcast remote controller should be in try/catch

hazelcast/reactor.py
=> fixing high cpu usage on asycore.loop

run-tests.ps1
Added PowerShell script to enable to execute Python client tests on Windows machine.
=> Added run-tests.ps1

docs/conf.py, docs/getting_started.rst, docs/index.rst, examples/map_soak.py, hazelcast/proxy/count_down_latch.py, setup.py, tests/proxy/count_down_latch_test.py
- Updated documentation to specify that client is now also supporting Python3.4+
- Added soak test for map
- Renamed await method of CountDownLatch with await_latch since await is a reserved keyword for Python3.7
=> updated documentation, added soak test and renamed await for python3 support changes

README.rst, docs/getting_started.rst, examples/README.md
updated README and add a section describes how to start hazelcast server to the documentation
=> updated README

docs/getting_started.rst, examples/README.md, examples/learning-basics/1-configure_client.py
replaced server with member and showed how to add multiple addresses to the configuration
=> update README and documentation

hazelcast/near_cache.py
Sorting eviction candidates with key instead of cmp increases eviction performance of near cache significantly
=> improve performance of near cache

hazelcast/client.py, hazelcast/config.py, hazelcast/connection.py, hazelcast/util.py, tests/property_tests.py
this pr implements client properties so that we can access all the available properties on one common class
fixes #114
=> implement client properties

hazelcast/__init__.py, hazelcast/client.py
updated the client version info to 3.10
=> update version info

docs/api/hazelcast.discovery.rst, docs/api/hazelcast.rst, docs/configuration.rst, hazelcast/config.py, hazelcast/connection.py, hazelcast/discovery.py
Updated doc strings to successfully build API docs using Sphinx
=> update documentation according to sphinx formatting

examples/org-website/atomic_long_sample.py, examples/org-website/custom_serializer_sample.py, examples/org-website/entry_processor_sample.py, examples/org-website/executor_service_sample.py, examples/org-website/global_serializer_sample.py, examples/org-website/identified_data_serializable_sample.py, examples/org-website/list_sample.py, examples/org-website/lock_sample.py, examples/org-website/map_sample.py, examples/org-website/multimap_sample.py, examples/org-website/portable_serializable_sample.py, examples/org-website/query_sample.py, examples/org-website/queue_sample.py, examples/org-website/replicated_map_sample.py, examples/org-website/ringbuffer_sample.py, examples/org-website/set_sample.py, examples/org-website/topic_sample.py
Updated the org-website examples to make them inline with
their Java client versions. Also, to make the examples more
pythonic, converted some camel case variables into snake case
ones along with some minor cleanups.
=> Update org-website examples

README.md
Updated the member tool documentation to include the
installation guides for Ubuntu, Debian, Red Hat and
CentOS.
=> Update the member tool documentation

hazelcast/protocol/client_message.py
This pr close connection when a message without a begin part is received instead of just logging it as the Java client.
=> close connection when a message without a begin part is received

hazelcast/discovery.py, tests/discovery/hazelcast_cloud_discovery_test.py
implementation of https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1951957067/Python+Client+AWS+PrivateLink+compatibility
=> add aws private link feature to cloud discovery

hazelcast/client.py, hazelcast/proxy/__init__.py
=> fix typo on the ringbuffer service constant

tests/proxy/map_test.py
... test since EntryLoaded event is added on IMDG 3.11
=> add 3.11 test category to test_add_entry_listener_item_loaded

hazelcast/__init__.py, setup.py
Also, set the development status to Beta.
=> Mark client version as 4.0.0b1

tests/proxy/distributed_objects_test.py
In the test, we were creating a map, and then immediately remove
the listener. This works most of the time, but sometimes, event
messages may arrive later, after we got a response from the get_map
request. If we remove the listener after the get_map response, but
before the late event, we will miss the event.
Test is modified to wait for the created event, then removing the
listener, then sleeping for a while and checking that there are no
further events.
Closes #253
=> Fix remove_distributed_object_listener test

hazelcast/reactor.py, tests/reactor_test.py
We forget to update the code that sets socket options while doing #219.
The code now handles the given socket options tuple correctly. Also,
added some tests that verifies this.
=> Fix setting configured socket options

README.rst
=> Update Hazelcast Cloud discovery documentation

docs/conf.py, docs/hazelcast.core.rst, docs/hazelcast.proxy.base.rst, hazelcast/client.py, hazelcast/config.py, hazelcast/cp.py, hazelcast/lifecycle.py, hazelcast/proxy/cp/atomic_long.py, hazelcast/proxy/cp/atomic_reference.py, hazelcast/proxy/cp/count_down_latch.py, hazelcast/proxy/cp/fenced_lock.py, hazelcast/proxy/cp/semaphore.py, hazelcast/proxy/list.py, hazelcast/proxy/map.py, hazelcast/proxy/multi_map.py, hazelcast/proxy/queue.py, hazelcast/proxy/replicated_map.py, hazelcast/proxy/set.py, hazelcast/proxy/transactional_map.py, hazelcast/proxy/transactional_multi_map.py, hazelcast/proxy/transactional_queue.py
There were couple of problems with the docstrigns and some private
APIs leaked into the public documentation.
The fix is verified manually by going over the produced HTML output.
=> Fix docstrings and API documentations

tests/ssl/hazelcast-default-ca.xml, tests/ssl/hazelcast-ma-optional.xml, tests/ssl/hazelcast-ma-required.xml, tests/ssl/hazelcast-ssl.xml, tests/ssl/mutual_authentication_test.py, tests/ssl/ssl_test.py
Backport of #247
We are using these new images to test 3.12.z nighhtly.
=> [BACKPORT] Update SSL protocol used in tests

README.rst, docs/index.rst
Added more content from the README to RTD index to make the page
more filled.
=> Improve the RTD homepage

hazelcast/client.py, hazelcast/connection.py, hazelcast/partition.py
Just trivial changes that don't alter code behavior.
=> Trivial Cleanup

docs/conf.py
Updated the version from 4.0 to 4.1
=> Update the client version used in docs

examples/README.md, examples/sql/sql_async_example.py, examples/sql/sql_example.py
Added a code sample that demonstrates different ways to interact
with the SQL service and the returned SqlResult objects.
Also, removed the explanation of the folders in the README because
it was out of sync with the current folder structure and was
not offering lots of value. It was mainly just repeating the
folder names.
=> [API-306] Add SQL code sample 

hazelcast/invocation.py
In the current code-base, we could retry invocations in the following
cases.
- In the `_do_invoke` function, when a target connection for the
invocation cannot be determined. This may happen in any other thread
than the reactor thread. But, in this case, a message is not sent
from the client (even, a message is not even put into one of the write
queue of a connection). Hence, the `sent_connection` of such invocations
is `None`.
- When an exceptional response is received from the server, which
always happen in the reactor thread.
- When a connection is closed, and we detect it in the clean resources
timer, which also always happens in the reactor thread.
Under this scenario, it was not possible for an invocation to
be retried multiple times, once for the exceptional response and one
for …
=> Fix invocation retry logic

hazelcast/client.py
Signed-off-by: Tree Davies <tdavies@darkphysics.net>
=> Clean up comment. Word 'access' used twice consecutively.

docs/getting_started.rst, docs/serialization.rst, docs/setting_up_client_network.rst, docs/using_python_client_with_hazelcast_imdg.rst
This is a PR that ports the changes done in #183 to the latest master.
=> Small text improvements

docs/using_python_client_with_hazelcast.rst, examples/sql/sql_json_example.py, hazelcast/protocol/builtin.py, hazelcast/protocol/codec/custom/hazelcast_json_value_codec.py, hazelcast/sql.py, start_rc.py, tests/integration/backward_compatible/sql_test.py
This PR adds implementation, tests, code samples, and documentation
for the SQL JSON column type.
Closes #508
=> [API-965] Implement SQL JSON support

tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py, tests/integration/backward_compatible/serialization/compact_test.py
This PR introduces backward compatibility support for compact tests
so that it can be safely ignored for older client/server versions.
=> Update compact tests for backward compatibility

examples/map/map_remove_all_example.py, hazelcast/proxy/map.py, tests/integration/backward_compatible/proxy/map_nearcache_test.py
=> [API-1499] Near-cache invalidation is added for remove_all and minor styling issues.

examples/serialization/simple_compact_serialization_example.py
This PR ports NodeJS code sample [hazelcast-nodejs-client#compact_serialization_sample.js](https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/code_samples/compact_serialization_sample.js) for Python.
There is already a nested compact example, we can rename files to distinguish or leave them as now.
=> Simple sample for Compact Serialization. [API-1333]

examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
This PR fixes some of the errors and typos in our Jupyter Notebook example.
=> Fix Jupyter notebook bugs. [API-1508]

hazelcast/protocol/__init__.py, start_rc.py, tests/integration/backward_compatible/predicate_test.py
Closes https://github.com/hazelcast/hazelcast-python-client/issues/666
=> [API-2187] Fixes API-2187
