- hazelcast/connection.py
- hazelcast/reactor.py
- tests/base.py
- tests/threading_test.py
Prevent busy waiting of reactor by checking for writes when there is something
in the queue to write. To decrease latency, directly write to socket if
queue is empty.
> prevent busy waiting of reactor thread

- examples/main.py
- tests/proxy/map_test.py
- tests/proxy/multi_map_test.py
- tests/proxy/replicated_map_test.py
- tests/reconnect_test.py
Refactor (continue) is done for indicating parameters which are functions.
First part of this refactor is: https://github.com/hazelcast/hazelcast-python-client/pull/19
> Refactor for addEntryListener methods of Map/MultiMap/ReplicatedMap

- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/replicated_map.py
ApiDoc added to map.py , multi_map.py and replicated_map.py with Python Sphinx format. 
add_entry_listener methods of these 3 classes are refactored for indicating parameters which are functions.
> ApiDoc for Map,MultiMap,ReplicatedMap with minor listener refactor

- tests/proxy/list_test.py
- tests/proxy/queue_test.py
- tests/proxy/set_test.py
Refactor (continue) is done for indicating parameters which are functions.
First part of this refactor is: https://github.com/hazelcast/hazelcast-python-client/pull/21 , https://github.com/hazelcast/hazelcast-python-client/pull/24 and https://github.com/hazelcast/hazelcast-python-client/pull/25
> Refactor for add_listener method in set_test, queue_test and list_test

- hazelcast/proxy/queue.py
- hazelcast/proxy/transactional_list.py
- hazelcast/proxy/transactional_map.py
- hazelcast/proxy/transactional_multi_map.py
- hazelcast/proxy/transactional_queue.py
- hazelcast/proxy/transactional_set.py
ApiDoc added to
- queue.py
- transactional_map.py
- transactional_set.py
- transactional_list.py
- transactional_queue.py
- transactional_multi_map.py with Python Sphinx format.
add_listener method of queue class is refactored for indicating parameters which are functions.
> ApiDoc for Queue and Transactional Proxies

- hazelcast/reactor.py
ignore raised Empty on reactor queue since queue is also consumed when timer is cancelled
fixes https://github.com/hazelcast/hazelcast-python-client/issues/57
> ignore raised Empty on reactor queue since queue

- hazelcast/cluster.py
- hazelcast/connection.py
authenticate manager should send uuid's if available. 
Initialise lastRead time of connection in connection constructor so that it will not be immediately closed down by heartbeat mechanism
fixes https://github.com/hazelcast/hazelcast-python-client/issues/59
fixes https://github.com/hazelcast/hazelcast-python-client/issues/60
> authenticate manager should send uuid's if available.

- hazelcast/reactor.py
This changes user configured intervals like heartbeat to be able
to work with smallest 1 seconds intervals.
Before that setting a value lower than 10 seconds was not working.
fixes https://github.com/hazelcast/hazelcast-python-client/issues/61
> Pull down the reactor loop wake up time from 10 sec to 1 sec

- tox.ini
Added `tox.ini` to be able to run tests in multiple environments.
The command `tox -e py27` runs the tests in Python 2.7 environment whereas `tox -e py36` runs in 3.6 version of Python.
The argument `--local` can be passed to `tox` command as `tox -e py27 -- --local`
As we're at starting point I've added just py27 and py36. We should ideally add more versions which we can do as we go along.
> Setting up tox

- hazelcast/partition.py
when partitions dict of partition service is set to empty dict, it may be used by other methods while still being updated by the for loop. This causes get_partition_owner to return None address and results in an exception as described in #76 
fixes #76
> remove the statement that sets partitions to empty dict

- hazelcast/connection.py
When client authenticates with the same address more than once,  [connections](https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/connection.py#L36) and [_pending_connections](https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/connection.py#L37) dictionaries of the connection manager are updated with the latests address-future pair as it should be. However, when on_auth or _connection_closed methods are called for each connection, these methods try to pop the same address from these dictionaries more than once which results in a KeyError.
We should try to pop the address but when KeyError happens we should simply pass since that address is already removed from these dictionaries by the previous method calls.
> fix pop behaviour of connection manager

- hazelcast/reactor.py
Hi,
Mostly my script is hanging when working on blocking map immediately after Hazlecast client created.
Below stack trace:
ERROR:Reactor:Error in Reactor Thread
Traceback (most recent call last):
File "C:\Tools\Python36\lib\site-packages\hazelcast\reactor.py", line 38, in _loop
self._check_timers()
File "C:\Tools\Python36\lib\site-packages\hazelcast\reactor.py", line 60, in _check_timers
self._timers.get_nowait()
File "C:\Tools\Python36\lib\queue.py", line 192, in get_nowait
return self.get(block=False)
File "C:\Tools\Python36\lib\queue.py", line 174, in get
item = self._get()
File "C:\Tools\Python36\lib\queue.py", line 230, in _get
return heappop(self.queue)
TypeError: '<' not supported between instances of 'Timer' and 'Timer'
When using pause time.sleep(1) before map consuming script …
> reactor Timer ordering

- hazelcast/client.py
- hazelcast/protocol/codec/lock_force_unlock_codec.py
- hazelcast/protocol/codec/lock_lock_codec.py
- hazelcast/protocol/codec/lock_try_lock_codec.py
- hazelcast/protocol/codec/lock_unlock_codec.py
- hazelcast/protocol/codec/map_force_unlock_codec.py
- hazelcast/protocol/codec/map_lock_codec.py
- hazelcast/protocol/codec/map_try_lock_codec.py
- hazelcast/protocol/codec/map_unlock_codec.py
- hazelcast/protocol/codec/multi_map_force_unlock_codec.py
- hazelcast/protocol/codec/multi_map_lock_codec.py
- hazelcast/protocol/codec/multi_map_try_lock_codec.py
- hazelcast/protocol/codec/multi_map_unlock_codec.py
- hazelcast/proxy/lock.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/util.py
this pr implements client lock idempotence by 
* adding a lock reference id generator to client
* making some lock related codecs retryable (lock/unlock/force unlock/try lock)
* adding a reference id attributes for these lock related operations on lock, map and multimap proxies.
> implement client lock idempotence

- hazelcast/serialization/portable/classdef.py
- hazelcast/serialization/portable/context.py
- hazelcast/serialization/predicate.py
- hazelcast/serialization/service.py
- tests/predicate_test.py
- tests/serialization/portable_test.py
Fixes registration of incompatible portable class definitions when nested portables used.
fixes #80
> Fix for Portable Serialization incompatible class definition when nested portables used

- hazelcast/util.py
- tests/predicate_test.py
Now 3-read_from_a_map.py works:
```
>>> import hazelcast
>>> import logging
>>> logging.basicConfig()
>>> logging.getLogger().setLevel(logging.INFO)
>>> config = hazelcast.ClientConfig()
>>> config.network_config.addresses.append("10.88.0.25:5701")
>>> config.network_config.addresses.append("10.88.0.26:5701")
>>> config.network_config.addresses.append("10.88.0.27:5701")
>>> config.group_config.name= 'production'
>>> client = hazelcast.HazelcastClient(config)
INFO:ClusterService:Connecting to Address(host=10.88.0.27, port=5701)
INFO:ConnectionManager:Authenticated with <hazelcast.reactor.AsyncoreConnection connected 10.88.0.27:5701 at 0x7f7000992c18>
INFO:ClusterService:New member list:
Members [3] {
Member [10.88.0.26]:5701 - 47f8c80b-4751-437b-8c08-7953f21615ee
Member [10.88.0.25]:5701 - …
```
> Issue #112: return non-None values

- hazelcast/connection.py
- hazelcast/reactor.py
- tests/client_test.py
- tests/heartbeat_test.py
- tests/reconnect_test.py
Client was not sending Ping to server when last read time is up-to-date. When server constantly pushes events to client, client does not send any ping to server. And consequently, server closes client because it does not send any ping. Client logic has changed so that it send pings if there is no outgoing packages recently, rather than looking at incoming packages.
fixes #108
> server should not close clients when client only listens

- hazelcast/discovery.py
- hazelcast/reactor.py
using logging.basicConfig would override the user's logging configuration. Removed logging.basicConfig to let the users to configure logging as they wish
> fix improper logging configuration

- tests/discovery/hazelcast_cloud_discovery_test.py
Nosetests was failing to detect the tests in the discovery folder due to missing init file. Added that file and corrected an error on one of the tests
> fix discovery test structure for nosetest

- tests/util.py
Sometimes SSL authentication process may take more than 1 seconds which
causes some SSL tests to fail due to timeout error. Increased the timeout
to 5 seconds to solve this issue.
> increase connection timeout for SSL tests from 1 seconds to 5 seconds

- tests/predicate_test.py
- tests/util.py
With this change, test classes or individual tests can be categorized
using tests/util.py/set_attr decorator. Categories can be set with
additional information 
```python
@set_attr(category=3.10)
```
or directly
```python
@set_attr(slow)
``` 
After categorizing tests, selected tests
can be run using nosetests. For example, tests without category or
test with the category value less than or equal to 3.8 can be selected
with the -A option of the nosetests  using Python-like syntax:
```bash
nosetests -A 'not category or category <= 3.8'
```
When no attribute option is provided to nosetests with -a or -A,
all tests will be selected automatically.
> Add an ability to categorize tests using attributes

- tests/ssl/mutual_authentication_test.py
mutual authentication feature comes with Hazelcast 3.8.1. Categorized mutual authentication tests to 3.8.
> categorize mutual authetincation tests

- docs/configuration.rst
- examples/cloud-discovery/hazelcast_cloud_discovery_example.py
- examples/ssl/ssl_example.py
- examples/ssl/ssl_mutual_authentication_example.py
- hazelcast/config.py
- hazelcast/reactor.py
- tests/ssl/ssl_test.py
- tests/util.py
SSL hostname check option is removed. When cafile is not set,
client will try to load default ca certificates from default
certificate locations.
> revert SSL hostname check and trust default ca certificates

- tests/ssl/mutual_authentication_test.py
- tests/ssl/ssl_test.py
- tests/util.py
Earlier enterprise check was not enough to determine the hazelcast
member type within the nosetests. Added the enterprise attribute to
the ssl related tests.
> Mark ssl tests as enterprise

- README.md
link to the getting started section of the hazelcast reference manual was removed mistakenly with the #143 . this pr adds that line again
> add missing line to the cluster section

- tests/proxy/flake_id_generator_test.py
`test_ids_are_from_new_batch_after_batch_is_exhausted` was failing sometimes because when we request small sized batches from the member one after another, member could send the newly requested batch with the base of `last batch's base + flake id step * batch size`. So, the test fails to differentiate between ids that are from the same batch and ids that are from the different batches but with the batch bases described above. I added a small sleep to make sure that member side sends a batch with a base greater than the base described above
> Fix the flake id generator test

- hazelcast/exception.py
This pr adds the missing exception classes to protocol exceptions. So, the users will get a more specific exception instead of a general hazelcast error when the member side throws an exception with a formerly unregistered error code.
> add missing protocol exceptions

- hazelcast/connection.py
- hazelcast/reactor.py
This is a partial fix for the issue described in #149 
Formerly, we were using an immutable bytes field as the buffer and each time reactor reads data from the socket, it were appending the received data to this buffer which was copying and re-creating the existing buffer data with the newly received data.  I changed that to the bytearray which is mutable in python so extra re-creation is eliminated . 
So overall, python client improved from ~50 seconds to ~35 seconds for the string test and from ~7 seconds to ~1 seconds for the bytes test in my computer
These were the results of the tests described in the #149 in my computer with the old code.
**Bytes test, java client**
```
Map Size = 10000
2019-02-19T14:36:48.760Z
Entries Iterated = 10000
2019-02-19T14:36:48.913Z
10849511800752
``` …
> use mutable bytearray instead of bytes as buffer

- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
add_entry_listener method of the map and multimap was mentioning something that does not follow the behaviour. when `include_value` is set to `false`, received event should not contain `old_value` or `value` but it was saying only the `old_value` will not be in the event
fixes #154
> update add_entry_listener documentation

- tests/predicate_test.py
- tests/ssl/mutual_authentication_test.py
- tests/statistics_test.py
test categories are converted to zero padded values
This is due to the fact that 3.10 is smaller than 3.6 as a float but in the IMDG versioning it is the newer one. This was causing problems in the client backward compatibility tests
> make the test categories integer instead of float

- tests/ssl/ssl_test.py
Hazelcast 3.12.1-SNAPSHOT is updated with a valid CA signed certificate (valid until 2021). This pr re-enables the ssl test where we check our client to trust default truststore.
> re-enable ssl test with the ca signed certificate

- tests/version_test.py
nosetests fails with the following exception when you run it twice within the same folder
```
Unable to load tests from file /home/jenkins/jenkins_slave/workspace/python-backward-compatibility/python/3.12/tests/git_info.json
```
basically, it tries to load tests from .json file. This fix removes the git_info.json which we created during the test so that we can run nosetests in the same directory more than once
> remove git_info.json after test

- hazelcast/connection.py
The default buffers are too small, causing any bigger payload size to queue up a lot on the application side and rely on polling to make it to the socket. As a result any latency benchmark with fat payloads is extremely slow.
Nagle was already off, similarly to Java, and left unchanged.
> Change default buffer sizes for connection similar to Java clients

- hazelcast/client.py
- hazelcast/config.py
- hazelcast/reactor.py
- hazelcast/serialization/input.py
- hazelcast/serialization/service.py
- tests/serialization/identified_test.py
- tests/serialization/portable_test.py
- Replaced BUFFER_SIZE import with a local variable which respects the configuration (if exists)
- Removed the timeout of the asyncore loop to allow for the thread to finish faster, allowing other threads to make progress sooner
- Replaced the double list iteration on the Input#read_byte_array with a bytearray, similar to what was done here https://github.com/hazelcast/hazelcast-python-client/pull/174 but this version doesn't wrap the result, rather leaves it as pure `bytearray` which is **slightly concerning because it changes the type of the function**, but it gives a good bit of extra boost.
> Minor networking / serialization changes for better latency on single calls

- examples/map/map_portable_versioning_example.py
I added a code sample under examples > map to demonstrate the multiversion support of portable serialization.
It creates 3 versions of Employee class and configures 3 clients, each of them with a different version of the class. The code sample shows that the first 2 versions are appropriate for Portable multiversion support (addition of new field), while the third version fails to be compatible due to incompatible type change of one of its fields (field type change from int to String).
> Portable Serialization Multiversion Support Code Sample

- README.md
This PR adds documentation for multiversion support of Portable Serialization in README inspired by the Reference Manual (with necessary changes for Python). It also improves the format of the headings and subheadings under Portable Serialization. It includes a versioning example for the Foo class as well.
> Portable versioning documentation

- hazelcast/connection.py
`test_smart_listener_remove_member` failed again in the backward compatibility tests. This time, the events does not received in some tests. After adding extra logging and testing again, (http://jenkins.hazelcast.com/job/python-backward-compatibility-metin/3/testReport/junit/tests.listener_test/ListenerTest/test_smart_listener_remove_member/) I saw the following logs.
```
Feb 11, 2020 02:39:59 PM HazelcastClient
INFO: [3.12.1] [dev] [hz.client_20] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast IMDG version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Feb 11, 2020 02:39:59 …
```
> add hash method to connection class

- hazelcast/connection.py
- hazelcast/listener.py
- hazelcast/protocol/client_message.py
- tests/client_message_test.py
Formerly, client was reusing the same client message for listener registration requests.  Since on each invoke, we set a new correlation id for the client messages, getting the correlation id as https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/listener.py#L103 were resulting in event registrations with duplicate correlation ids
> operate on a copy of the listener registration request

- hazelcast/listener.py
- tests/proxy/queue_test.py
The implementation of the Future runs the callbacks after notifying the threads waiting on the condition. Because of that, the blocking call `result` on futures may be returned before executing the callbacks. This was causing the `test_remove_entry_listener_item_added` on `queue_test.py` to fail randomly. In the runs that fail, following scenario occurs:
1. `reg_id = self.queue.add_listener(include_value=False, item_added_func=collector)` is called. The result is set and the test runner continues with the next line but the callbacks are not fully executed yet (callbacks are executed on the reactor thread whereas tests run on the main thread)
2. `self.queue.remove_listener(reg_id)` is called. This calls `deregister_listener` method of the listener service. The problematic line is the …
> fix race on the listener registration

- hazelcast/invocation.py
- tests/invocation_test.py
fixes #191 
Also adds a test to verify that the TimeoutError is actually raised. Test uses the fact that there is no partition owner for the id of -1, so invocation will be retried. We sleep 2 * INVOCATION_TIMEOUT_SECONDS inside the mocked has_partition_id method to simulate the timeout scenario.
> fix typo on the invocation service

- hazelcast/proxy/base.py
- hazelcast/proxy/map.py
- tests/proxy/hazelcast_mapstore.xml
- tests/proxy/map_test.py
- tests/util.py
Added missing EntryLoaded event alongside the missing mapstore tests.
The test for the loaded event uses `SampleMapStore` in the `com.hazelcast.client.test` package. It firsts puts a data to map with TTL. After 0.1 second, data is not available on the map but available on the map store. So, the get method call causes the event to fire by loading the entry from the underlying MapStore
fixes #172
> Add missing loaded event

- README.md
- examples/monitoring/distributed_object_listener.py
- hazelcast/client.py
- hazelcast/core.py
- hazelcast/proxy/__init__.py
- hazelcast/proxy/base.py
- hazelcast/util.py
- tests/base.py
- tests/proxy/distributed_objects_test.py
This PR contains the code samples, documentation and implementation for the distributed object listener and get_distributed_objects method of the client.
Just like the Java client, call to the get_distributed_objects method clears the local instances of the destoyed proxies.
> Implement distributed object listener and get_distributed_objects method

- README.md
- hazelcast/client.py
- hazelcast/config.py
- hazelcast/connection.py
- hazelcast/errors.py
- hazelcast/future.py
- hazelcast/invocation.py
- hazelcast/protocol/client_message.py
- setup.py
- test-requirements.txt
- tests/backup_acks_test.py
- tests/config_test.py
- tests/future_test.py
- tests/invocation_test.py
Boomerang backups implementation, documentation, tests, required configuration options, namely,
`backup_ack_to_client_enabled`, `operation_backup_timeout` and
`fail_on_indeterminate_operation_state` are added.
Also, another test dependency is added to make mocking the failure scenarios easier.
Added dependency, `mock`, comes with the standard library on Python3.3+, but due to
support for Python2.7, it is added.
depends on #221
> Implement boomerang backups

- README.md
- examples/cp/atomic_reference_example.py
- hazelcast/cp.py
- hazelcast/proxy/cp/atomic_long.py
- hazelcast/proxy/cp/atomic_reference.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/queue.py
- hazelcast/serialization/data.py
- hazelcast/util.py
- tests/proxy/cp/atomic_long_test.py
- tests/proxy/cp/atomic_reference_test.py
For the AtomicReference, implementation, code samples, documentation and
tests are added. It also includes some minor docstring fixes regarding
the lists in some places and some missing checks and documentation fixes
for the AtomicLong.
depends on #223
> CP Subsytem - Atomic Reference

- README.md
- docs/hazelcast.proxy.cp.atomic_reference.rst
- docs/hazelcast.proxy.cp.count_down_latch.rst
- docs/hazelcast.proxy.cp.rst
- examples/cp/count_down_latch_example.py
- hazelcast/cp.py
- hazelcast/invocation.py
- hazelcast/proxy/cp/count_down_latch.py
- hazelcast/util.py
- tests/invocation_test.py
- tests/proxy/cp/count_down_latch_test.py
Adds the implementation, documentation, code samples, and test of
CP CountDownLatch.
Also, the invocation service is edited to return `OperationTimeoutError`
instead of `HazelcastTimeoutError` in case of invocation timeouts
as the Java client does.
depends on #224
> CP Subsystem - CountDownLatch

- README.md
- docs/hazelcast.proxy.cp.fenced_lock.rst
- docs/hazelcast.proxy.cp.rst
- examples/cp/fenced_lock_example.py
- examples/org-website/lock_sample.py
- hazelcast/client.py
- hazelcast/cp.py
- hazelcast/errors.py
- hazelcast/future.py
- hazelcast/listener.py
- hazelcast/protocol/__init__.py
- hazelcast/proxy/cp/__init__.py
- hazelcast/proxy/cp/fenced_lock.py
- hazelcast/proxy/executor.py
- hazelcast/proxy/map.py
- hazelcast/util.py
- tests/cp_test.py
- tests/future_test.py
- tests/proxy/cp/fenced_lock_test.py
Implementation, tests, documentation and code samples for the Fenced Lock
is added.
Also, the session manager for session aware CP proxies is implemented
fully along with its test suit. The unused parts of the session manager
will be used with the Semaphore proxy.
> CP Subsystem - Fenced Lock

- README.md
- docs/hazelcast.proxy.cp.rst
- docs/hazelcast.proxy.cp.semaphore.rst
- examples/cp/semaphore_example.py
- hazelcast/cp.py
- hazelcast/proxy/cp/__init__.py
- hazelcast/proxy/cp/semaphore.py
- setup.py
- test-requirements.txt
- tests/proxy/cp/hazelcast_cpsubsystem.xml
- tests/proxy/cp/semaphore_test.py
Implementation, tests, documentation and code samples for both the
session aware and sessionless semaphore proxies are added.
Also, another test dependency to parameterize tests is added.
> CP Subsystem - Semaphore

- tests/base.py
- tests/cluster_test.py
Added a test that verifies when all members of the Hot Restart enabled
cluster is restarted, client's member list is not broken.
The implementation is fixed within the initial 4.0 PR, so adding
just the test to verify that the implementation is correct.
closes #164
> Test member list after hot restart

- README.md
- examples/map/map_paging_predicate_example.py
- hazelcast/core.py
- hazelcast/hash.py
- hazelcast/protocol/__init__.py
- hazelcast/protocol/builtin.py
- hazelcast/protocol/codec/custom/anchor_data_list_holder_codec.py
- hazelcast/protocol/codec/custom/paging_predicate_holder_codec.py
- hazelcast/protocol/codec/map_entries_with_paging_predicate_codec.py
- hazelcast/protocol/codec/map_key_set_with_paging_predicate_codec.py
- hazelcast/protocol/codec/map_values_with_paging_predicate_codec.py
- hazelcast/proxy/map.py
- hazelcast/serialization/predicate.py
- hazelcast/util.py
- tests/predicate_test.py
This is the port of #212
to the 4.0 branch. However, there are some differences from that PR.
- Documentation of the feature is a little bit different since the client
side sorting is removed.
- Tests are more-or-less ported directly with a few additions for
input validations. However, the above PR was using `six.assertCounEqual`
for assertions which checks equality but not order. For paging predicate
tests, it makes more sense to check ordering.
- Client side codecs and holder classes for PagingPredicates and AnchorDataLists
are added.
- Some public methods, like `get_anchor`, `set_anchor`, `get_nearest_anchor_entry`
is removed. `get_anchor` is defined on the public API on the Java side but I think
it does not provide any functionality to the user.
Also, some missing `six.moves.range` …
> Implement PagingPredicate

- hazelcast/serialization/predicate.py
- tests/proxy/map_paging_predicate_test.py
`list.clear()` is not available on Python2.7. We have missed that
since `reset()` method is not tested. According to the standard library
documentation, `list.clear()` is equivalent to `del list[:]`, so I replaced
it with that.
Also, added some missing tests and replaced `six.assertCountEquals`
with `assertEquals` to check ordering of elements along with equality.
> Fix PagingPredicate#reset and its tests

- hazelcast/serialization/portable/classdef.py
- hazelcast/serialization/service.py
- tests/serialization/portable_test.py
When class definitions for two different classes with the same class id
but different factory ids are registered, we were throwing an error
indicating that there are duplicate registrations. However, we should
allow such cases.
Apart from the fix for that, the PR also includes a test case for
null portable serialization.
Closes #199
> Fix class definition registrations with the same class id

- hazelcast/serialization/portable/classdef.py
- hazelcast/serialization/service.py
- tests/serialization/portable_test.py
Backport of #235
When class definitions for two different classes with the same class id
but different factory ids are registered, we were throwing an error
indicating that there are duplicate registrations. However, we should
allow such cases.
Apart from the fix for that, the PR also includes a test case for
null portable serialization.
> [BACKPORT] Fix class definition registrations with the same class id

- hazelcast/reactor.py
Formerly, we were doing a logic like the following: Check the
timer in front of the priority queue of timers. If it is expired,
call the callback and pop it from the queue. However, this logic
is flawed because the timers queue was accessed from multiple threads.
So, it may be the case that, we check the timer in front of the queue,
run its callback, then, some other thread adds another timer to the
queue concurrently and it is put in front of the queue. Now, when the
reactor thread pops the item in front of the queue, it will be the newly
added timer, before its callback being executed.
To solve this, we use a double buffering approach. A thead-safe queue
is used to store newly added timers which can be efficiently modified
on both ends on multiple threads. Then, the reactor thread …
> Fix the race on the timers

- hazelcast/hash.py
- hazelcast/serialization/data.py
- tests/murmur_hash_test.py
We were always passing a bytes-like object to the murmur hash function
but, we were copying it from the HEAP_DATA_OVERHEAD(8) offset, which
can be huge. I removed that copy and tuned the offsets according to our
HEAP_DATA_OVERHEAD.
Another parameter of the function was the data size. For valid Data
objects, this is always equal to the `len(buffer) - HEAP_DATA_OVERHEAD`.
This parameter is removed and this length is calculated inside the
murmur hash function now.
Also, inlined the _fmix function call and removed the unnecessary
method calls on hash_to_index function.
> Optimize murmur hash calculation

- hazelcast/invocation.py
It is not really useful for the end user to see the each message
that clients send. It might be useful for us on some occasions,
so I left it as a commented line. Commenting it resulted in
approx. %1-2 throughput increase.
> Remove logging on sending each client message

- hazelcast/serialization/base.py
- hazelcast/serialization/data.py
- hazelcast/serialization/input.py
- hazelcast/serialization/output.py
- tests/data_test.py
- tests/serialization/serialization_test.py
- tests/serialization/string_test.py
See the individual commit messages for the explanation.
> Serialization service improvements

- hazelcast/client.py
Documentation about logging_config and logging_level were not
removed in #229. This removes them, since they are not usable
anymore.
> Remove leftover docstring elements

- tests/ssl/hazelcast-default-ca.xml
- tests/ssl/hazelcast-ma-optional.xml
- tests/ssl/hazelcast-ma-required.xml
- tests/ssl/hazelcast-ssl.xml
- tests/ssl/mutual_authentication_test.py
- tests/ssl/ssl_test.py
OpenSSL 1.1.1 disables TLSv1 by default. We will be using it
on our new docker images. So, SSL tests are updated to use TLSv1.2 instead.
> Update SSL protocol used in tests

- README.rst
- examples/monitoring/distributed_object_listener.py
- examples/org-website/topic_sample.py
- examples/topic/topic_example.py
- hazelcast/client.py
- hazelcast/invocation.py
- hazelcast/listener.py
- hazelcast/protocol/client_message.py
- hazelcast/proxy/list.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/queue.py
- hazelcast/proxy/replicated_map.py
- hazelcast/proxy/set.py
- hazelcast/proxy/topic.py
- tests/proxy/distributed_objects_test.py
Listener service was waiting for the result of the future
in a blocking way and, returning the registration id string.
This is not in line with our other APIs in which we provide
non-blocking API.
Also, the slight behaviour change applied to Java client is
ported to Python client. https://github.com/hazelcast/hazelcast/pull/17646
> Make ListenerService return Future

- setup.py
We could say this we also support these versions after running
the test suite on them successfully. See
http://jenkins.hazelcast.com/view/Clients/job/python3.8-lab-master/2/console
and
http://jenkins.hazelcast.com/view/Clients/job/python3.9-lab-master/1/console
> Add Python 3.8 and 3.9 to supported versions

- tests/backup_acks_test.py
It might be the case that the replica node could not finish its
partition table initialization when it receives the backup operation
request from the primary node. That can cause the backup request to
be dropped which can result in test failure since there won't be any
backup acks from the replica node.
This won't be needed when the https://github.com/hazelcast/hazelcast/issues/9398
is fixed. Until then, a call like `map.get(1)` should be enough as a
workaround.
See Also: https://github.com/hazelcast/hazelcast-nodejs-client/pull/693
> Avoid possible race on BackupAcksTest

- hazelcast/serialization/input.py
- tests/serialization/input_test.py
The Functionality of missing `skip_bytes` is implemented and some
unit tests are added.
Closes #255
> Implement ObjectDataInput#skip_bytes

- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/queue.py
- hazelcast/proxy/transactional_map.py
- hazelcast/util.py
- tests/proxy/map_test.py
- tests/proxy/queue_test.py
- Validated the default time values with the Java client. We were
sending -1 second for unset values, however the server
was expecting -1 millisecond.
- Updated some parameter names or docstrings to make them more
clear.
- Implemented support for max idle in map `put`, `put_transient`,
`put_if_absent` and `set`. Also added some basic tests.
- Made queue `add` to return `IllegalStateError` to make it
more consistent with other clients.
Closes #258
> Go over the default time values

- hazelcast/reactor.py
- tests/reactor_test.py
This is an optimization for the non-blocking usage where there are
multiple in-flight messages. We now coalesce them into a single buffer
and try to write it to the wire.
Before coming up with this solution, I tried a couple of different ones.
Here is the list of the main ones, and why they didn't work out:
- Having a single, pre-allocated bytearray per connection, and copying
message bytes into it. Even with the usage of `memoryview`s, slicing and
copying were so expensive.
- Implementing framed outbound client messages, and writing frame bytes
into a write buffer in the reactor thread. That resulted in approx. %5
throughput increase for balanced workloads.
This way of implementation results in approx. %10 throughput increase for
balanced workloads.
> Coalesce multiple client messages if possible before writing

- hazelcast/invocation.py
- tests/reconnect_test.py
If the invocation is meant to be sent to a certain connection and
we receive TargetDisconnectedError(in case of the detection of
a closed connection) or IOError(in case of actual IO error) for
it, we should not retry.
> Fix invocation retry mechanism

- hazelcast/invocation.py
We were using a new correlation id on invocation retries, which
can cause problems because the invocation is modified in-place.
We may have pending invocation entries with the key of correlation
id of X while the correlation id we would get from the client
message of the invocation is Y (Y > X).
It is changed so that the invocation is retried but now uses the
same correlation id.
> Use the same correlation id on invocation retries

- README.rst
- docs/index.rst
As pointed out in the code review for #266, there were
unnecessary newlines around the top-level callback function
definition, but we left it as it is since PEP8 recommends
such newlines.
Changed that part to use lambdas so that we can get rid of
the newlines.
> Get rid of the unnecessary newlines in the README

- hazelcast/connection.py
- hazelcast/cp.py
- hazelcast/listener.py
There was a bug in the implementation of the connect_to_all_members
timer. In the loop, we were not capturing the address variable
correctly. As recommended in https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result
we are now binding the variable while creating the closure.
> Capture the address in the loop of connect_to_all_members timer

- hazelcast/listener.py
Port of the following Java PR
https://github.com/hazelcast/hazelcast/pull/17147
I couldn't add the test in that PR because that requires blocking
the communication between some members, which is not possible via
the remote controller.
> Correctly handle memberlist in case of split brain

- tests/proxy/map_test.py
Increased the assertion timeout for the set_ttl test from 1 second
to 5 seconds. It is also 5 seconds in the master branch.
Closes #277
> Increase assertion timeout for set_ttl test

- docs/client_connection_strategy.rst
- docs/securing_client_connection.rst
- docs/using_python_client_with_hazelcast_imdg.rst
- hazelcast/client.py
- hazelcast/config.py
- hazelcast/proxy/map.py
- hazelcast/util.py
- tests/config_test.py
This PR adds the ability to use enum literals in the config
to make it easier to set these options, without importing anything.
When a value for enum is set, we first check if it is an actual
value for an enum(i.e., 0 for SSLProtocol.SSLv2). If it is, we
directly use that. If not, and the given configuration value is
a string, we try to get the enum member associated with that name.
If it matches to any member(i.e., SSLv2 for SSLProtocol.SSLv2),
we get the value associated with it and set it as the value.
If none of the above works, we throw TypeError as before.
Closes #228
> Add ability to use enum literals in config

- tests/proxy/distributed_objects_test.py
In the test, we were creating a map, and then immediately remove
the listener. This works most of the time, but sometimes, event
messages may arrive later, after we got a response from the get_map
request. If we remove the listener after the get_map response, but
before the late event, we will miss the event.
Test is modified to wait for the created event, then removing the
listener, then sleeping for a while and checking that there are no
further events.
Backport of #261
Closes #280
> [3.12.z] - Fix remove_distributed_object_listener test

- hazelcast/proxy/__init__.py
- hazelcast/proxy/base.py
- hazelcast/proxy/cp/__init__.py
- hazelcast/proxy/cp/atomic_long.py
- hazelcast/proxy/cp/atomic_reference.py
- hazelcast/proxy/cp/count_down_latch.py
- hazelcast/proxy/cp/fenced_lock.py
- hazelcast/proxy/cp/semaphore.py
- hazelcast/proxy/executor.py
- hazelcast/proxy/flake_id_generator.py
- hazelcast/proxy/list.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/pn_counter.py
- hazelcast/proxy/queue.py
- hazelcast/proxy/replicated_map.py
- hazelcast/proxy/ringbuffer.py
- hazelcast/proxy/set.py
- hazelcast/proxy/topic.py
- hazelcast/proxy/transactional_list.py
- hazelcast/proxy/transactional_map.py
- hazelcast/proxy/transactional_multi_map.py
- hazelcast/proxy/transactional_queue.py
- hazelcast/proxy/transactional_set.py
- pyproject.toml
Linted the files at `hazelcast/proxy` and removed its exclusion.
> Lint hazelcast/proxy

- hazelcast/client.py
- hazelcast/cluster.py
- hazelcast/config.py
- hazelcast/connection.py
- hazelcast/core.py
- hazelcast/cp.py
- hazelcast/discovery.py
- hazelcast/errors.py
- hazelcast/future.py
- hazelcast/hash.py
- hazelcast/invocation.py
- hazelcast/listener.py
- hazelcast/near_cache.py
- hazelcast/partition.py
- hazelcast/predicate.py
- hazelcast/reactor.py
- hazelcast/six.py
- hazelcast/statistics.py
- hazelcast/transaction.py
- hazelcast/util.py
- pyproject.toml
Linted files located at the hazelcast folder and removed its
exclusion from the `pyproject.toml`.
> Lint files located at hazelcast folder

- docs/client_connection_strategy.rst
- hazelcast/client.py
- hazelcast/config.py
- tests/config_test.py
As discussed within the team, cluster connection timeout is
increased to 120 seconds to handle cluster restarts correctly
without an extra configuration in environments like kubernetes.
> Increase cluster connection timeout

- hazelcast/client.py
- hazelcast/cluster.py
- hazelcast/connection.py
- hazelcast/invocation.py
- hazelcast/lifecycle.py
- hazelcast/listener.py
- hazelcast/near_cache.py
- hazelcast/statistics.py
- tests/invocation_test.py
- tests/proxy/map_nearcache_test.py
- tests/statistics_test.py
I don't like the idea of making the config public because it is
not read-only after the creation yet. Instead, it is made private
for the time being. We may reconsider making it public later.
> Make client.config private

- README.rst
- docs/conf.py
- docs/copyright.rst
- tests/proxy/cp/hazelcast_cpsubsystem.xml
- tests/proxy/hazelcast_crdtreplication_delayed.xml
- tests/proxy/hazelcast_litemember.xml
- tests/proxy/hazelcast_mapstore.xml
- tests/soak_test/hazelcast.xml
Updated the copyright year in corresponding places to 2021 and removed
unnecessary copyright headers from some xml files that are used in
tests.
> Update copyright year to 2021

- docs/conf.py
- hazelcast/__init__.py
- setup.py
Set the client version to 4.0 and development status to
production/stable after completing the release process.
> Set the cliet version to 4.0

- README.rst
It seems that we forget to change the clients name while copying
the content from the Node.js client's README.
This change updates the name of the client.
> Correct the client name in the README

- README.rst
It seems that we forget to change the clients name while copying
the content from the Node.js client's README.
This change updates the name of the client.
> [4.0.z] Correct the client name in the README

- hazelcast/invocation.py
In the clean resources timer, if we detect that the connection that
the invocation is sent is not alive, we resolve it with
TargetDisconnectedError. For those invocations, there is no need
to check the backup timeout.
Closes #325
> Do not check backup timeout for resolved invocations

- hazelcast/invocation.py
In the clean resources timer, if we detect that the connection that
the invocation is sent is not alive, we resolve it with
TargetDisconnectedError. For those invocations, there is no need
to check the backup timeout.
Backport of #347
> [4.0.z] Do not check backup timeout for resolved invocations

- hazelcast/reactor.py
- tests/reactor_test.py
When the socket.connect fails immediately, we were not removing
the connection from the dispatchers map and closing the
in memory write buffer.
> Cleanup resources when the connection attempt fails immediately

- docs/client_connection_strategy.rst
- hazelcast/client.py
- hazelcast/config.py
- hazelcast/connection.py
- hazelcast/cp.py
- hazelcast/listener.py
- tests/config_test.py
- tests/connection_strategy_test.py
We decided to set the default cluster connection timeout to
infinite to have a better user experience out-of-the-box
for most of the users/use cases. Note that, this is a breaking
change for the users who rely on the client to shutdown after
some time. Affected users might set the `cluster_connect_timeout`
to a finite value.
Also, updated the default value of the `retry_multiplier` to back off
more after the client tries to connect to the target cluster for
some time.
Closes #335 
Closes #306
> Set the cluster connection timeout to infinite by default

- docs/serialization.rst
- docs/using_python_client_with_hazelcast_imdg.rst
- examples/map/map_portable_query_example.py
- examples/map/map_portable_versioning_example.py
- examples/org-website/custom_serializer_sample.py
- examples/org-website/executor_service_sample.py
- examples/org-website/identified_data_serializable_sample.py
- examples/org-website/portable_serializable_sample.py
- examples/org-website/query_sample.py
- examples/serialization/global_serialization_example.py
- examples/serialization/identified_data_serializable_example.py
- examples/serialization/portable_example.py
- hazelcast/predicate.py
- hazelcast/serialization/api.py
- hazelcast/serialization/input.py
- hazelcast/serialization/output.py
- hazelcast/serialization/portable/classdef.py
- hazelcast/serialization/portable/reader.py
- hazelcast/serialization/portable/writer.py
- hazelcast/serialization/serializer.py
- tests/predicate_test.py
- tests/proxy/cp/atomic_reference_test.py
- tests/proxy/executor_test.py
- tests/proxy/map_test.py
- tests/serialization/binary_compatibility/reference_objects.py
- tests/serialization/custom_global_serialization_test.py
- tests/serialization/identified_test.py
- tests/serialization/morphing_portable_test.py
- tests/serialization/portable_test.py
- tests/soak_test/map_soak_test.py
As decided with the team, methods containing the word `utf` is
renamed with `string`. (`read_utf` -> `read_string` etc.).
For backwards compatibility, old methods are still there but we
have a deprecation documentation for them.
Closes #342 
Closes #367
> Replace utf with string in public API

- hazelcast/invocation.py
- tests/invocation_test.py
We were mistakenly overwriting the invocation timeout to None
even if it is explicitly set to something else.
We are now respecting the given timeout value in the invocation
constructor.
> [4.0.z] Do not overwrite invocation timeout in the constructor

- hazelcast/invocation.py
- tests/invocation_test.py
We were mistakenly overwriting the invocation timeout to None
even if it is explicitly set to something else.
We are now respecting the given timeout value in the invocation
constructor.
> Do not overwrite invocation timeout in the constructor

- tests/base.py
- tests/client_test.py
- tests/proxy/cp/count_down_latch_test.py
- tests/proxy/cp/semaphore_test.py
- tests/reactor_test.py
- tests/soak_test/map_soak_test.py
- tests/statistics_test.py
- tests/util.py
* [time.time()](https://docs.python.org/3/library/time.html#time.time) returns the time based on system clock, which can go back for several reasons such as 
* synchronization from a web server
* leap seconds
* Thus, using time.time() for profiling is not the correct option. The difference might even be negative due to reasons above.
* Instead of using time.time(), [time.monotonic()](https://docs.python.org/3/library/time.html#time.monotonic) should be used as it is based on cpu clock and always increases.
> Use time.monotonic() instead of time.time() for profiling 

- docs/index.rst
As requested, we now link to the Features section of the documentation
in the index, instead of the hazelcast.org link.
> Link to the Features section in the documentation index

- tests/integration/backward_compatible/client_test.py
- tests/integration/backward_compatible/proxy/cp/atomic_long_test.py
- tests/integration/backward_compatible/proxy/cp/atomic_reference_test.py
- tests/integration/backward_compatible/proxy/cp/count_down_latch_test.py
- tests/integration/backward_compatible/proxy/cp/semaphore_test.py
- tests/integration/backward_compatible/statistics_test.py
- tests/integration/backward_compatible/util.py
- tests/util.py
On certain tests, a newer server might be required to test functionality.
Formerly, we were using attributes to distinguish such tests but this
way, it is easier to handle all cases.
Also, removed some unneeded compatibility code.
> Skip tests when a newer server is expected

- hazelcast/cp.py
- tests/unit/proxy/cp/cp_proxy_manager_test.py
It is not possible to run the CP data structures on the metadata
group name. We now fail-fast if someone tries to use the `METADATA`
as the CP group name. Also, the group name comparison made
case-insensitive.
Closes #374
> Fail fast on the METADATA group name for CP data structures

- hazelcast/util.py
Abstract classes Sequence and Iterable are meant to be imported
from `collections.abc` instead of `collections` starting from
Python 3.3. Since the minimum supported Python version for the
client is 3.4, we can safely try to import it from the new location
and fallback to the old location if the import fails. It will only
fail for Python 2.7 in which it is fine to import those abstract
classes from `collections`.
Closes #384
> Do not use deprecated abstract classes from collections

- hazelcast/serialization/portable/classdef.py
- tests/unit/serialization/portable_test.py
With this change, `add_xxx_field` methods of the ClassDefinitionBuilder
checks the class name first, and if it already registered, raises
HazelcastSerializationError.
Also, missing docstrings for the `add_xxx_field` methods are added.
Closes #330
> Do not allow using duplicate field names in ClassDefinitionBuilder

- hazelcast/client.py
- hazelcast/connection.py
- hazelcast/invocation.py
- hazelcast/listener.py
- hazelcast/reactor.py
- tests/integration/backward_compatible/heartbeat_test.py
- tests/unit/invocation_test.py
Similar to the Java-side fix, we now use the member UUID as the source
of the truth and allow connections to be opened to the same address
more than once. We just make sure that, on the active connections
dictionary, there is just one entry per member via its UUID.
This change simplifies a great deal of things. We now, don't need
a dictionary for pending connections and managing the state of
the connection manager is easier. Also, with this change, we now
make sure that, for the same member, we don't have more than one
active connection in the case of the issue reported on the Java-side
PR.
Also, improved the logging in case of the connection errors.
Closes #333
Closes #378
> Simplify connection manager

- tests/integration/backward_compatible/reconnect_test.py
Based on the Java-side `ClientRegressionWithRealNetworkTest`, added tests
that verify the client can continue to work when it is configured with
different network interfaces than the member side. Note that, this
is just a test that verifies the behavior of the client is correct.
Closes #148
> Add a test that verifies client can work when it is configured with different network interface than member

- tests/integration/backward_compatible/proxy/distributed_objects_test.py
Improved the distributed object tests slightly by using assertTrueEventually.
Although we have never seen it before, this approach is safer.
> Use assertTrueEventually in distributed object tests

- hazelcast/__init__.py
- tests/__init__.py
Due to a bug on the older client releases, the backward compatibility
tests sometimes fail on the client.shutdown() call. The reasoning
is explained in the https://github.com/hazelcast/hazelcast-python-client/issues/378
and linked PRs.
To solve this problem, we monkey patch the shutdown method, try to
call it, if it fails with an expected exception, cleanup the
leftovers and return without an error.
Shutdown calls generally happen on the teardown methods of the
tests so that we do not leak any clients to other tests. This
change should not cause any problems in actual tests.
This change should not cause any change in the current codebase
since we increased the client version to the next version in this PR (to 4.1)
> [API-337] Monkey patch client shutdown on tests for older client versions

- tests/integration/backward_compatible/reconnect_test.py
Client shutdown calls were missing for some of the reconnect tests.
Added that and added a secondary shutdown mechanism in case something
goes wrong in the tests (like assertion failures) and we couldn't shutdown
the client.
> Properly shutdown clients in reconnect tests

- start_rc.py
Updated the version to 4.1.4-SNAPSHOT to use the renewed
certificates.
> Update Hazelcast version used in tests

- hazelcast/proxy/ringbuffer.py
- tests/integration/backward_compatible/proxy/hazelcast.xml
- tests/integration/backward_compatible/proxy/ringbuffer_test.py
- tests/util.py
Before this, read_many was returning an immutable lazy list of
items read. However, there were more information sent by the server
which we were omitting.
Now, read_many returns an instance of ReadResult, which the user
can get the read count, size, next sequence to read from and
item sequences. Note that, this is not a breaking change. ReadResult
inherits from the ImmutableLazyDataList and hence is a list. So, the
users of this API can use their code as it is without any change when
they upgrade to 4.1. New users might benefit from the new APIs provided.
Also added a filter parameter to read_many, refactored the implementation
and updated some docstrings.
> [API-338] Improve Ringbuffer#read_many

- docs/features.rst
- docs/using_python_client_with_hazelcast_imdg.rst
- examples/org-website/reliable_topic_sample.py
- examples/reliable-topic/reliable_topic_example.py
- hazelcast/client.py
- hazelcast/config.py
- hazelcast/proxy/base.py
- hazelcast/proxy/reliable_topic.py
- tests/integration/backward_compatible/proxy/reliable_topic_test.py
- tests/integration/backward_compatible/ssl_tests/ssl_test.py
Apart from that, also corrected a few docstring issues.
> [API-340] Add documentation and code samples for the ReliableTopic

- tests/soak_test/map_soak_test.py
The Python script we are using were trying to import something
from the test package. That was not good because inside the
`__init__` file of the test package, we define a global logger
config that we want to use in tests.
But, in the SOAK test, we are using some other logger config.
To make the logger output work, import is removed and the functionnality
is directly copy-pasted, since it is something really small.
> Fix SOAK test script

- hazelcast/connection.py
Before this change, we were logging the cluster connect timeout
as it is. Its default value is equal to `sys.maxsize`, so the
logs were like
```
... cluster connect timeout: 92233720368547758067s ...
```
We now output `INFINITE` for the default value.
```
... cluster connect timeout: INFINITE
```
If the user provides a different value, it will be printed
as it is now.
Closes #404
> Pretty print cluster connect timeout in logs

- hazelcast/client.py
- hazelcast/partition.py
We were not documenting the public attributes of the client. Now,
we are doing it with their types, which has more documentation.
Also, made them read-only properties.
> Make public attributes of the client properties and document them

- docs/features.rst
- docs/using_python_client_with_hazelcast_imdg.rst
Added similar documentation to the IMDG Reference Manual
for the SQL feature. Modified examples and some parts of
the documentation to make it suit the Python client.
>  [API-305] Add SQL documentation 

- hazelcast/cluster.py
- hazelcast/connection.py
- hazelcast/listener.py
- tests/integration/backward_compatible/cluster_test.py
- tests/util.py
With this change, we now clear the memberlist when the cluster changes,
instead of just clearing the memberlist version so that, we can
fire events when a member with HotRestart enabled restarts with
the same UUID. Added a test that verifies this behavior.
Also, removed an unnecessary usage of the `clear_member_list_version`
method.
closes #371
> [API-466] Fire membership events when HotRestart is enabled

- docs/using_python_client_with_hazelcast_imdg.rst
- hazelcast/sql.py
The SQL column type documentation was not up-to-date with the
latest decisions about using `str`. Updated them and put the
format of the `str` to make them easier to use.
> Fix the SQL column type documentation

- docs/using_python_client_with_hazelcast_imdg.rst
- hazelcast/sql.py
Updated the documentation to reflect the format of this type
more accurately.
- Made the microsecond part optional, since it won't be displayed
if it is equal to zero.
- Made the timezone offset sign one-of `+` or `-`.
> Update the TIMESTAMP_WITH_TIMEZONE documentation

- tests/integration/backward_compatible/lifecycle_test.py
This test failed in Github Actions runners. The reason of the failure
is that, we try to check the received events right after shutting down
the member. It might be the case that, the member is shutdown, but
it is not visible to the client yet.
To tackle that, we now use `assertTrueEventually` to verify that
we receive the event.
> Fix `test_lifecycle_listener_receives_disconnected_event`

- tests/integration/backward_compatible/connection_strategy_test.py
- tests/integration/backward_compatible/proxy/reliable_topic_test.py
There were two problems identified in the backward compatibility
tests.
- The `reliable_topic_test` was added to the client in v4.1 and marked
correctly. However, there were no guards on the imports. So, it failed
against client v4.0. We added import guards for problematic ones.
- In `test_async_reconnect_mode`, we added the listener after restarting
the member. In some situations, we might connect member back, even
before adding the listener, and miss the event. Now, the listener is
added before restarting the member.
> Backward compatibility related test fixes

- tests/integration/backward_compatible/proxy/reliable_topic_test.py
In the `ReliableTopicTest`, we should only add the reliable
topic config elements for 4.1+ clients.
Note that, this change is required because the unittest will skip
tests after running the setUpClass method.
> Add reliable topic configs only for 4.1+ clients

- run_tests.py
In the test runner, we just check if there is an entry named
`HAZELCAST_ENTERPRISE_KEY` in the environment variables. For our
codecov runner, for PRs, it is in fact there but set to an empty value.
Hence, it was passing the check mistakenly. Now, we don't start
the enterprise tests, if there is an empty enterprise key.
> Check the enterprise key properly in the test runner

- hazelcast/errors.py
HazelcastInstanceNotActiveError was mistakenly decorated as retryable
but in fact it is not. See https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/core/HazelcastInstanceNotActiveException.java
> Make the HazelcastInstanceNotActiveError non-retryable

- hazelcast/connection.py
- tests/integration/backward_compatible/proxy/map_test.py
In the frame reader, we were storing the frame size including the
header (frame size + flags which is 6 bytes). Also, after reading
the frame size from the header, we were incrementing the bytes_read.
That approach works for small frames, that we can read with one go,
but was not working for frames that are large. For the same frame,
the next time we call read_frame, the length of the reader (the data
we haven't read from the buffer) was equal to frame size, but the
variable frame_size was equal to `frame_size + HEADER_SIZE`. So,
we were not reading the data that was actually there due to some
faulty length check.
We were able to read the data that is in the buffer after some long
time, when the response for the client ping request comes as it
was incrementing the length of the reader …
> Fix frame reader

- docs/conf.py
- hazelcast/__init__.py
- tests/integration/backward_compatible/proxy/map_test.py
Set the client version to 4.2.1 and mark the minimum client version
of the newly added test as 4.2.1.
> Mark the client version as 4.2.1 for the next development cycle

- tests/integration/backward_compatible/proxy/map_test.py
Puts the aggregator imports inside a try block to not fail
the tests in clients that don't have this feature implemented.
> Fix map tests for backward compatibility

- .gitignore
- run_tests.py
When there are some scripts in the main directory, the test runner
might get stuck on executing it and fail to start tests.
To improve the local development experience, I added the directory
of the tests to the test runner so that it only tries to run
tests from there.
Also, added some common virtual environment directories to the .gitignore.
Closes #443
> Improve test runner

- docs/api/aggregator.rst
- docs/api/modules.rst
- docs/features.rst
- docs/using_python_client_with_hazelcast_imdg.rst
- examples/aggregators/aggregators_example.py
- hazelcast/aggregator.py
- hazelcast/core.py
- hazelcast/serialization/objects.py
- hazelcast/serialization/service.py
- tests/integration/backward_compatible/proxy/map_test.py
There were couple of missing things in the community PR for the
aggregators. This is an attempt to fix those. Namely,
- Some missing aggreagators are added (distinct, min_by, max_by).
For them, some identified factories are also added, as they
have different return values.
- Aggregator module is added to the API documentation
- A code sample is added
- Docstrings are updated
- Documentation is updated and corrected
> Follow-up aggregators implementation

- hazelcast/serialization/objects.py
- hazelcast/serialization/service.py
- tests/integration/backward_compatible/proxy/reliable_topic_test.py
Formerly, we didn't implement IDS for Address as it was not needed
in the Python client but with the implementation of ReliableTopic,
it was possible to get Address instances via fields the messages
sent by the server.
To fix this, we introduce another class that inherits from the Address
and return it when someone tries to read such field. We take such measures
to deal with the cyclic import errors. If we were to implement IDS for
Address in the core module, and try to register it in the serialization
module, we would have a cyclic import.
Note that, this is basically a workaround but it is enough for our needs.
We need a proper refactoring of our modules to get rid of such problems
and maybe we can do that in 5.0.
> Make Address readable via IdentifiedDataSerializer

- docs/securing_client_connection.rst
Added the documentation for the external package we provide
for Kerberos authentication.
> Add documentation for the Kerberos authentication

- docs/api/modules.rst
- docs/api/projection.rst
- docs/features.rst
- docs/using_python_client_with_hazelcast_imdg.rst
- examples/projections/projections_example.py
- hazelcast/core.py
- hazelcast/projection.py
- hazelcast/proxy/map.py
- tests/integration/backward_compatible/proxy/map_test.py
- tests/unit/projection_test.py
This is a follow up PR after merging the Projections PR. This is
a combination of lots of small things.
- Add documentation to properties of `MapEntry` so that they are
displayed
- Move map#project so that we maintain alphabetical order
- Add some corner case tests for projections and aggregations
- Used asserCountEqual on projection tests so that the tests will
be more durable, even if we add more items to map
- Add missing API documentation for projections
- Fix API documentation of projections around the return value documentations
- Add unit tests for the invalid projection inputs
- Make the projections code snippet simpler
- Add a code sample for projections
> Projections follow up

- docs/conf.py
- docs/using_python_client_with_hazelcast_imdg.rst
- hazelcast/__init__.py
- hazelcast/protocol/builtin.py
- hazelcast/sql.py
- start_rc.py
- tests/base.py
- tests/integration/backward_compatible/proxy/distributed_objects_test.py
- tests/integration/backward_compatible/sql_test.py
This is an initial PR for the v5 SQL. It consists minimal changes
required to test the v5 SQL. Follow up PRs will come after that.
Here are the list of changes made:
- Set client version to 5.0
- Update remote controller scripts so that it uses hazelcast+hazelcast-sql
JARs instead of hazelcast-all, since hazelcast-all is not produced anymore.
Also, update some documentation about it.
- Use ints to represent years in DATE column type
- Use built-in types for DATE, TIME, TIMESTAMP, TIMESTAMP WITH TIMEZONE, and DECIMAL
which are datetime.date, datetime.time, datetime.datetime,
datetime.datetime(with non-None tzinfo), and decimal.Decimal.
- Update SQL tests and add some Jet tests
- Fix distributed objects tests by filtering internal objects out.
> [API-700] v5 SQL: Initial PR

- hazelcast/connection.py
- hazelcast/sql.py
- hazelcast/util.py
- requirements-dev.txt
- tests/integration/backward_compatible/authentication_tests/authentication_test.py
- tests/integration/backward_compatible/cluster_test.py
- tests/integration/backward_compatible/proxy/cp/atomic_long_test.py
- tests/integration/backward_compatible/proxy/cp/atomic_reference_test.py
- tests/integration/backward_compatible/proxy/map_test.py
- tests/integration/backward_compatible/proxy/reliable_topic_test.py
- tests/integration/backward_compatible/proxy/ringbuffer_test.py
- tests/integration/backward_compatible/sql_test.py
- tests/integration/backward_compatible/statistics_test.py
- tests/unit/sql_test.py
- tests/util.py
In v5, the logic behind selecting a query connection is changed
a little bit.
Formerly, we were relying on the load balancers to fetch the next
data member. Now, we are selecting a random connection from the
largest same-version (ignoring the patch version) member group.
This way, SQL will be available on the client-side during rolling
upgrade scenarios.
> [API-701] v5 SQL: Use different logic for getting query connections

- hazelcast/util.py
- tests/integration/backward_compatible/sql_test.py
- tests/unit/load_balancer_test.py
These methods were specially added for 4.2 SQL, but they are unused
in v5. Hence, we are removing the unused methods and reverting the
changes we made around the load balancer implementations and tests.
Note that, it is perfectly safe to remove these methods in Python.
If there were users that implemented these methods, they can use
their code without changing anything.
> [API-702] v5 SQL: Remove unused load balancer methods

- .github/workflows/test_runner.yml
Right now, the documentation generator job does not fail when there
is a warning. We wanted to fail on such warnings because the warning
shown might result in missing content on the generated docs.
We achieve this by supplying the `-W` SPHINXOPTS. Also, we provide
`--keep-going` to not just fail on the first warnings we see
and try to keep going. This way, we would see all warnings. Note that,
the exit code will still be non-zero if there are some warnings and
the job will fail.
> Make document generation job more strict

- .github/workflows/nightly_runner.yml
- .github/workflows/test_runner.yml
- tests/integration/backward_compatible/proxy/cp/count_down_latch_test.py
- tests/util.py
In the nightly tests, there were some failures.
- In Windows runners, `test_await_latch_with_timeout` was failing
randomly. My assumption is that, due to low time resolution, sometimes
we were getting equal values instead of larger values. I changed
the condition from `>` to `>=`. Also, I changed the failure message
so that, the next time it fails we will see the exact values.
- Removed `python -m pip install --upgrade pip` statements as the Python
runners already have the latest pip available to them. If we try to
upgrade pip to the latest version, for some older Python versions
it fails because those Python versions reached their EOL and pip
no longer tries to maintain compatibility for them.
- Modified the nightly runner so that, when the os is `ubuntu-latest`
and the Python version is …
> Fix Github Actions runners

- .github/workflows/nightly_runner.yml
This time, nightly runners complained with the following error:
```
The workflow is not valid. .github/workflows/nightly_runner.yml (Line: 7, Col: 14): Unexpected symbol: '"ubuntu-latest"'. Located at position 14 within expression: matrix.os == "ubuntu-latest" && matrix.python-version == "3.4" && "ubuntu-18.04" || matrix.os
```
Looking at the https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions,
they use single quotes inside of the expressions for strings.
Hence, this time, I did the same.
Also, I put `workflow_dispatch` option to `on` section so that
I can manually start the tests. This way, we don't have to wait
until the next morning to see the effects of the changes we made.
> Fix nightly runners

- tests/integration/backward_compatible/proxy/cp/count_down_latch_test.py
Increased the timeout from 0.1 second to 1 second. Also, in Windows
due to low time resolution, we lowered the compared value slightly.
With increased timeout, comparing to a slightly lower value should
be OK since it shows that we are in fact waiting for the timeout.
Note that, the miscalculation comes from the fact that, the calculation
for the time passed in the Python side is precise to +-16ms. See
https://bugs.python.org/issue44328 and the Windows documentation for
the methods used by the CPython for more information.
> Increase timeout used in `test_await_latch_with_timeout`

- requirements-test.txt
This is a required change because the Python 3.4 on Windows cannot
install one of our dev dependencies. (psutil)
The reasoning is that, psutil does not push Python 3.4 wheel files
for Windows for a long time, and while trying to install the dependency
from the source code, Python 3.4 on Windows fails. I tried to upgrade
pip version on this setup to latest compatible version but that didn't
help.
Downgrading the psutil version is also not an option because as I said,
they are not publishing the wheels for 3.4 for a long time (couple of years).
What I did instead is to provide some requirement specifiers for psutil.
Basically, we would install it in any Python version other than 3.4 or
any OS other than `nt` (windows). Note that, lack of this dev dependency
simply means that we will not …
> Adjust test requirements based on Python version and OS

- docs/setting_up_client_network.rst
- examples/external-smart-client-discovery/external_smart_client_discovery_example.py
- hazelcast/client.py
- hazelcast/cluster.py
- hazelcast/config.py
- hazelcast/connection.py
- hazelcast/core.py
- hazelcast/protocol/__init__.py
- hazelcast/protocol/codec/custom/endpoint_qualifier_codec.py
- hazelcast/proxy/reliable_topic.py
- tests/integration/backward_compatible/cluster_test.py
- tests/integration/connection_manager_translate_test.py
- tests/unit/config_test.py
This PR implements the client-side support for the external smart
client discovery. With this PR, the Python client will be able
to use public addresses reported by the cluster members even
if the client and the cluster are in different networks.
To use it, one has to enable `use_public_addresses` option by setting
it to `True`, and passing at least one public address of the cluster
members to the `cluster_members` config. Client will initiate the
cluster connection using the provided public address, and will
discover the rest of the cluster using the public addresses reported
by them.
Protocol PR: https://github.com/hazelcast/hazelcast-client-protocol/pull/394
> [API-582] Implement external smart client discovery

- docs/using_python_client_with_hazelcast_imdg.rst
- requirements-dev.txt
Updates the SQL documentation with the changes done in the reference
manual. This change mainly reorganizes the documentation and adds some
notes about the new capabilities. For the details, we directed users
to the reference manual so that we don't have to duplicate most parts
of the reference manual which can change frequently.
> [API-704] v5 SQL: Update documentation

- tests/integration/backward_compatible/sql_test.py
The tests failed on nightly runners due to an error like this
```
ERROR: test_execute_with_params (tests.integration.backward_compatible.sql_test.SqlServiceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "D:\a\hazelcast-python-client\hazelcast-python-client\tests\integration\backward_compatible\sql_test.py", line 164, in test_execute_with_params
self._create_mapping()
File "D:\a\hazelcast-python-client\hazelcast-python-client\tests\integration\backward_compatible\sql_test.py", line 118, in _create_mapping
result.update_count().result()
File "D:\a\hazelcast-python-client\hazelcast-python-client\hazelcast\future.py", line 60, in result
six.reraise(self._exception.__class__, self._exception, self._traceback)
File …
```
> Escape map names while creating mappings

- hazelcast/protocol/codec/custom/sql_error_codec.py
- hazelcast/sql.py
- tests/integration/backward_compatible/sql_test.py
- tests/unit/sql_test.py
Recently, an enhancement is implemented on the server-side to provide
suggestions to execute in case of SqlErrors. The main use case is to
provide the `CREATE MAPPING` query suggestions in case there exists
a map and there are some entries on it.
The documentation of this feature will be provided in the upcoming
SQL documentation update PR.
Protocol PR: https://github.com/hazelcast/hazelcast-client-protocol/pull/398
Closes #470
> [API-876] Provide suggestions for the `HazelcastSqlError`

- hazelcast/sql.py
- tests/integration/backward_compatible/sql_test.py
This is a required change to be able to use parts of the row,
even if we cannot deserialize some column values.
Also, lazy deserialization is a plus on its own.
To accomplish this, similar to the Java client, I have changed the
code so that, we try to deserialize column values when we
call `get_object` or `get_object_with_index`. Note that,
just like the Java client
```
row.get_object("smth")
row.get_object("smth")
```
will result in two deserializations.
We could easily solve this with an extra object per row (something
like LazyDeserializable class with two fields: serialized and deserialized
where once we deserialize it, it assigns the result to deserialized and
return it for the subsequent calls). But, I didn't want to go that way due
to extra object cost.
Closes #447
> [API-875] Deserialize `SqlRow`s lazily

- hazelcast/future.py
- hazelcast/listener.py
- hazelcast/util.py
- tests/unit/future_test.py
With this PR, we will wait for all the listener deregistration
requests to finish before returning `True` to the user.
It is mainly a precaution to the possible problems that might result
in services that expect sync removal of listeners.
While doing that, I have also dived into one of our technical debts
and corrected the implementation of the `combine_futures`.
It now waits for all futures to complete in all scenarios, as it should be,
and sets the result to the first exceptional completion, if some of
the input futures complete as such.
Closes #448
> [API-879] Wait for listener deregistration requests

- hazelcast/protocol/codec/map_remove_interceptor_codec.py
- hazelcast/proxy/map.py
- tests/integration/backward_compatible/proxy/map_test.py
Also, added a test for the `add_interceptor` method.
Protocol PR: https://github.com/hazelcast/hazelcast-client-protocol/pull/399
> Add missing `remove_interceptor` API to the Map

- hazelcast/sql.py
- Removed the warning about the BETA status
- Similar to Java client, simplified the API doc as most of the
things we mention here is already mentioned in the actual
SQL documentation
- Add a warning about enabling Jet and adding `hazelcast-sql`
to the member's classpath
- And other minor updates.
> Update SqlService API documentation

- docs/using_python_client_with_hazelcast_imdg.rst
- examples/sql/sql_example.py
- hazelcast/sql.py
- tests/integration/backward_compatible/sql_test.py
This is mainly an enhancement for easier access for columns in the row.
Now, the `SqlRow` implements the `__getitem__` magic method.
Implementation of the method simply performs a type check and calls
`get_object_with_index` if the type of the passed parameter is an
integer type. For any other type, it calls `get_object`. Hence,
it will throw for any other type than `int` or `str`.
Also, put a piece of information about this new way to the documentation
& code samples.
> Make `SqlRow` support `[]` operator

- docs/using_python_client_with_hazelcast_imdg.rst
- examples/sql/sql_async_example.py
- examples/sql/sql_example.py
- hazelcast/sql.py
- tests/integration/backward_compatible/sql_test.py
- tests/unit/sql_test.py
Up until now, we were returning the `SqlResult` immediately after
initiating the query to the server, without waiting for the first
response.
The server might not be able to handle some consequences of such
an API. To align the behavior with the Java implementation and
make it more intuitive, we now wait for the initial response
in the `execute` and `execute_statement` methods.
With that change, the return types are changed from `SqlResult` to
`Future[SqlResult]`. Also, I got rid of the Futures in the return types
of the methods over the `SqlResult` except for the `close`, as the
`close` might in fact go to the server.
With this change, I cleaned up the implementation so that it reflects
the new behavior better.
Also, we now return a rejected Future immediately if the first execute
the …
> [API-900] Wait for the initial response in the SQL queries

- docs/using_python_client_with_hazelcast_imdg.rst
This PR updates the SQL documentation at the client-side with
the recent changes done to the reference manual.
We mostly follow a similar structure, but we go into more detail
for Portable and JSON queries in these documents as these are
the most intuitive ways to run SQL queries from the Python client.
Note that, the code samples in this PR are written according to
recent PRs, some of which not merged yet.
> [API-899] Update SQL documentation according to recent changes

- examples/sql/sql_example.py
- hazelcast/sql.py
- start_rc.py
- tests/integration/backward_compatible/sql_test.py
- tests/unit/sql_test.py
We were providing two APIs two execute SQL queries.
- `execute` with a string query and parameters
- `execute_statement` with `SqlStatement` parameter two have more
control over the query execution.
We decided to get rid of the `execute_statement` and `SqlStatement`
and provide ability to pass keyword arguments to `execute` to customize
the behavior of the queries. With that change, the properties of
`SqlStatement` is now keyword arguments.
Also, upgraded the server version to 5.0 as 5.0 is released.
> [API-901] Get rid of the `execute_statement` API for SQL

- hazelcast/cluster.py
We couldn't find a reason to apply membership events with the
same memberlist version while evaluating this part of the code
base in the Java client.
Here, we are doing the same and making the check more strict
Closes #485
> Apply membership events only if the memberlist version is greater than the current version

- hazelcast/client.py
- hazelcast/listener.py
- tests/integration/backward_compatible/proxy/cp/__init__.py
There was a test failure due to StackOverflow error while trying
to re-register the cluster view listener.
The chain of events that caused the overflow are following:
- client.shutdown() is called
- we have a couple of connections
- while closing the connection manager, we close connections one-by-one
- we close the connection that the cluster view listener is registered to
- after closing this, we trigger a re-registration attempt and try to invoke
the listener registration in one of the remaining connections
- since the client is shutting down, the invocations are failed immediately
- while trying the add a callback to the invocation future, since it
is already done, we call the callback immediately
- that causes an infinite chain of registration attempts and leads the
StackOverflow …
> Fix re-registration logic of the ClusterViewListener

- hazelcast/sql.py
There was a duplicate `usage` section that we forgot to delete.
This PR removes that.
> Remove leftover `usage` section

- tests/integration/backward_compatible/client_test.py
- tests/integration/backward_compatible/heartbeat_test.py
- tests/integration/backward_compatible/listener_test.py
- tests/integration/backward_compatible/proxy/flake_id_generator_test.py
- tests/integration/backward_compatible/smart_listener_test.py
There were some tests that are taking too much time to run. Most
of the time, we either create too many members or sleep too much
while waiting on some assertions.
This is a PR to tackle with that. I went over the long running
tests and either shorten the duration of the waits (of course without
breaking the test) or reduced the number of members we create without
changing the behavior of the tests.
> Reduce test duration for the integration tests

- tests/integration/backward_compatible/heartbeat_test.py
- tests/integration/backward_compatible/listener_test.py
We had some test failures on the backward compatibility runs, mainly
due to the fact that, the failing tests were not resilient enough
to timing problems.
In the `HeartbeatTest::test_heartbeat_stopped_and_restored`, it was
possible that the responses coming from the server for the previous
heartbeat requests to override what we wrote as the `last_read_time`.
In the `ListenerAddMemberTest::test_add_member`, it was possible that
the `map#put` would complete before the listener is registered to the
newly added connection.
> Make the tests more resilient to timing problems

- hazelcast/client.py
- hazelcast/compact.py
- hazelcast/listener.py
- hazelcast/partition.py
- hazelcast/proxy/base.py
- hazelcast/proxy/cp/__init__.py
- hazelcast/proxy/cp/atomic_long.py
- hazelcast/proxy/cp/atomic_reference.py
- hazelcast/proxy/executor.py
- hazelcast/proxy/list.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/queue.py
- hazelcast/proxy/reliable_topic.py
- hazelcast/proxy/replicated_map.py
- hazelcast/proxy/ringbuffer.py
- hazelcast/proxy/set.py
- hazelcast/proxy/topic.py
- hazelcast/proxy/transactional_list.py
- hazelcast/proxy/transactional_map.py
- hazelcast/proxy/transactional_multi_map.py
- hazelcast/proxy/transactional_queue.py
- hazelcast/proxy/transactional_set.py
- hazelcast/serialization/compact.py
- hazelcast/sql.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
- tests/integration/backward_compatible/serialization/compact_test.py
- tests/unit/sql_test.py
For compact serialization to work, we have to control the results
of the serialization. Also, for the responses we got from the server,
we have to eagerly deserialize them, and retry after receiving the
schema from the cluster.
With this PR, we make sure that on each API we support compact serialization,
we check the result of the `to_data` call to see if it throws or not.
If it throws, we try to send the schema to the cluster and retry.
Also, this PR adds tests for all the APIs we support compact serialization.
For now, we didn't implement eager deserialization for the APIs that
return `ImmutableLazyDataList`, so there are no tests for such APIs.
To be able to add those tests, we would need quite a bit of compact
serializable classes written in Java. This PR includes aforementioned
Java …
> [API-521] Add support for compact serialization to public APIs

- .github/workflows/test_runner.yml
- README.rst
- docs/development_and_testing.rst
- docs/getting_started.rst
- examples/README.md
- hazelcast/cluster.py
- hazelcast/config.py
- hazelcast/connection.py
- hazelcast/core.py
- hazelcast/future.py
- hazelcast/listener.py
- hazelcast/proxy/__init__.py
- hazelcast/proxy/cp/atomic_reference.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/pn_counter.py
- hazelcast/proxy/reliable_topic.py
- hazelcast/proxy/replicated_map.py
- hazelcast/reactor.py
- hazelcast/serialization/compact.py
- hazelcast/serialization/portable/classdef.py
- hazelcast/serialization/service.py
- hazelcast/statistics.py
- hazelcast/transaction.py
- hazelcast/util.py
- requirements-dev.txt
- tests/unit/reactor_test.py
There were around 60 errors shown in the mypy checks about the various
minor problems across the client code base. This PR corrects
those errors and adds a check for the mypy to PR builder workflow.
Note that, for now, we are only checking the type hints in the
hazelcast directory (client's code base). Tests and examples are not
passing the mypy checks for now. We can improve this incrementally,
and add them in the future.
Also, we are not using the strict flag of the mypy, due to not
type hinting the internals yet. Hopefully, we will have that
in the future.
> Fix mypy errors

- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
- tests/unit/serialization/binary_compatibility/reference_objects.py
Some test imports causes a problem running the backward compatibility tests on master with older Python client releases. Converted those imports to no-ops.
> Fixed test imports for older releases.

- .github/workflows/coverage_runner.yml
Tests are only running when a PR is opened, but it wasn't set in the old workflow. If needed tests should be triggered when PR is reopened and new commits come. When types are not set it uses default ones `opened` `reopened` `synchronize`
> trigger type 'opened' is removed

- .github/workflows/coverage_runner.yml
- black.toml
- docs/serialization.rst
- examples/serialization/compact_serialization_example.py
- examples/sql/sql_compact_example.py
- hazelcast/client.py
- hazelcast/config.py
- hazelcast/serialization/api.py
- hazelcast/serialization/compact.py
- hazelcast/serialization/service.py
- run_tests.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
- tests/integration/backward_compatible/serialization/compact_test.py
This PR:
* Changes `compact_serializers` configuration to be a list of `CompactSerializer`.
* Adds `get_class` method to the base `CompactSerializer`.
* Updates related docs and tests.
* Trivially updates `run_tests.py` to pass given comand line arguments to `pytest`.
> Updated Compact Configuration

- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
- tests/integration/backward_compatible/serialization/compact_test.py
We need to skip 5.2 server versions if the client version is <5.2.
This PR updates the tests to skip on such scenarious.
> Update Compact related tests for backward compatibility tests

- examples/map/map_remove_all_example.py
- hazelcast/protocol/codec/map_remove_all_codec.py
- hazelcast/proxy/map.py
- tests/integration/backward_compatible/proxy/map_test.py
map.remove_all method is introduced and implemented with following details:
- remove_all public API and implementation are added
- remove_all code sample is added
- related unittests are added to map_test
Closes #520
> map.remove_all implementation

- tests/unit/near_cache_test.py
This test was failing frequently on nightly builds on Windows.
After some inspection, from the logs, I saw that the `key-0` is expired, despite it being accessed in every iteration of the loop.
The problem is, time resolution in Windows is pretty bad. It has milliseconds precision, and the test is prone to failure with that. It is entirely possible that the test runs fairly quickly, fill the near cache with entries within a millisecond, and when we are about to evict some entries to open up space for new keys, `key-0` might be in the eviction pool, due to us not being able to differentiate the last access times with such a low precision.
The actual solution to this problem would be to use high-precision timers added in the later versions of the Python, but I leave this one to later, we …
> Use LFU eviction policy in NearCacheTestCase#test_put_get

- tests/integration/connection_manager_test.py
As reported by Serkan on a similar issue for Node.js, the `192.168.0.1` is reachable from time to time in the Windows runners in Github Actions.
Being able to reach this address causes some tests to fail. (See the recent nightly runs for the failing tests)
As a solution, we are using a truly unreachable address, similar to what we did for Node.js client.
> Use truly unreachable address in ConnectionManagerTranslateTest

- docs/conf.py
- hazelcast/__init__.py
- tests/integration/backward_compatible/proxy/map_nearcache_test.py
- tests/integration/backward_compatible/proxy/map_test.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
These tests were added, but there were no checks for them for the older client versions in the backward compatibility tests.
This PR bumps the client version to 5.2.0 and adds the necessary checks.
Also, a test for Compact compatibility is added for this functionality.
> Make map#remove_all tests backward compatibility aware

- hazelcast/serialization/compact.py
- tests/integration/backward_compatible/serialization/compact_test.py
- tests/unit/serialization/compact_test.py
Fixes https://github.com/hazelcast/hazelcast-python-client/issues/556
Added check for None serializer, on it, throw a HazelcastSerializationError in this case.
Added a new test for missing nested serializer case, it checks if a HazelcastSerializationError has been thrown.
> Nested compact field's serializer can be None if it is not registered [API-1416]

- examples/topic/topic_example.py
- hazelcast/protocol/codec/topic_publish_all_codec.py
- hazelcast/proxy/topic.py
- tests/integration/backward_compatible/proxy/topic_test.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
Added codec for publish all message.
> publish_all() method for Topic [API-1529]

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
There seems to be a temporary issue on the availability of the Python 3.6 version in the ubuntu-22.04 (latest).
Till that issue is resolved, we should pin the Ubuntu version to 20.04, as it is the latest version that has Python 3.6 today.
closes #596
> Set the Ubuntu version used in workflows to 20.04 [API-1745]

- hazelcast/protocol/builtin.py
- hazelcast/protocol/codec/multi_map_put_all_codec.py
- hazelcast/proxy/multi_map.py
- tests/integration/backward_compatible/proxy/multi_map_test.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
- Existing PR has an issue with workflows and [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast-python-client?pullRequest=573). Therefore, I opened a new one.
- If I add test (which was commented out in compact compatibility test), it throws an exception in that space but passed fine in mutlimap test.
- I tried to resolve remaining reviews. 
```
compact_compatibility_test.py::MultiMapCompactCompatibilityTest::test_put_all_get ERROR [100%]
test setup failed
cls = <class 'tests.integration.backward_compatible.serialization.compact_compatibility.compact_compatibility_test.MultiMapCompactCompatibilityTest'>
@classmethod
def setUpClass(cls) -> None:
cls.rc = cls.create_rc()
>       if compare_server_version_with_rc(cls.rc, "5.1") < 0: …
```
> Add put_all() to MultiMap [API-1235]

- docs/api/modules.rst
- docs/config.rst
- docs/configuration_overview.rst
- docs/index.rst
- examples/configuration/kwargs_configuration_example.py
- examples/configuration/object_configuration_example.py
- hazelcast/client.py
- hazelcast/config.py
- hazelcast/proxy/flake_id_generator.py
- hazelcast/proxy/reliable_topic.py
- hazelcast/reactor.py
- hazelcast/serialization/service.py
- tests/integration/backward_compatible/client_test.py
- tests/unit/config_test.py
- tests/unit/invocation_test.py
- tests/unit/near_cache_test.py
- tests/unit/reactor_test.py
- tests/unit/serialization/binary_compatibility/binary_compatibility_test.py
- tests/unit/serialization/compact_test.py
- tests/unit/serialization/custom_global_serialization_test.py
- tests/unit/serialization/identified_test.py
- tests/unit/serialization/int_serialization_test.py
- tests/unit/serialization/morphing_portable_test.py
- tests/unit/serialization/portable_test.py
- tests/unit/serialization/serialization_test.py
- tests/unit/serialization/serializers_test.py
- tests/unit/serialization/string_test.py
These were converted into private classes during the 4.0 migration,
as we were only supporting keyword arguments for the client configuration.
However, that led to a poor user experience, as we had to use `**kwargs`,
instead of listing all the configuration elements in the client constructor.
(IDEs become painfully slow once we list all keyword arguments, as there
are too many of them)
The solution to this problem is to make the Config classes public API
and make the client able to use it directly.
```python
config = Config()
config.cluster_name = "dev2"
client = HazelcastClient(config)
```
We provide full type hints for config elements.
> Convert `Config` classes to public API [API-1280]

- examples/packages/pandas_example.py
- examples/pandas/pandas_example.py
Hi 👋
Fixes: https://github.com/hazelcast/hazelcast-python-client/issues/601
This PR adds a code sample to document how Pandas DataFrame can be used with Hazelcast Python Client. There are multiple ways to store the DataFrame in Hazelcast, I tried to list them all.
I am new to open source, so I would really appreciate all comments if you have any suggesstion. 
Thanks in advance.
> Add code sample to show how Hazelcast works with Pandas DataFrames.

- hazelcast/serialization/compact.py
- hazelcast/serialization/service.py
- tests/unit/serialization/compact_test.py
This PR introduces couple of updates to the implementation
- Schema now holds a regular dict, instead of OrderedDict for faster lookups and simpler implementation
- Prevent duplicate field names by adding a check to the schema writer
- Disallowing compact serializers to override builtin serializer
closes https://github.com/hazelcast/hazelcast-python-client/issues/559
closes https://github.com/hazelcast/hazelcast-python-client/issues/579
> Introduce various updates for the Compact serialization [API-1564]

- docs/serialization.rst
- hazelcast/serialization/api.py
This PR updates the Compact related documentation.
- Corrects a few stale places in the API docs
- Removes BETA annotations from the API docs
- Adds a documentation about the nullable-primitive interoperability
This PR does not remove the limitations section in the reference docs so that we can use the list there to make sure that the Compact works nicely with those APIs, before releasing 5.2.
closes https://github.com/hazelcast/hazelcast-python-client/issues/565
closes https://github.com/hazelcast/hazelcast-python-client/issues/582
> Update Compact documentation [API-1564]

- hazelcast/connection.py
- tests/integration/backward_compatible/serialization/compact_test.py
- tests/integration/connection_manager_test.py
In split-brain scenarios, the cluster id stays the same for different halves of the split.
When the client disconnects from the first half it was connected to and reconnects to the other half, from the point of view of the client, it connects to the same cluster.
However, it might very well be the case that, the client has sent some state to the first half of the cluster, and that state must be replicated to the other half when the client reconnects to it.
This is especially needed for Compact schemas.
In this PR, we are sending the client state to the cluster after reconnections, regardless it is connected back to possibly the same cluster with the same id or not.
We couldn't add proper split brain tests, as the remote controller does not have that ability yet. However, I have added a …
> Send client state to cluster in reconnections [API-1564]

- hazelcast/serialization/api.py
- hazelcast/serialization/compact.py
- tests/unit/serialization/compact_test.py
We have decided to only support single item type for Compact arrays.
This PR adds this check, updates the documentation and adds a test for the change.
closes https://github.com/hazelcast/hazelcast-python-client/issues/564
> Do not allow different item types while writing Compact arrays [API-1564]

- docs/serialization.rst
- hazelcast/proxy/list.py
- hazelcast/proxy/map.py
- hazelcast/proxy/multi_map.py
- hazelcast/proxy/queue.py
- hazelcast/proxy/reliable_topic.py
- hazelcast/proxy/replicated_map.py
- hazelcast/proxy/ringbuffer.py
- hazelcast/proxy/set.py
- hazelcast/proxy/transactional_map.py
- hazelcast/proxy/transactional_multi_map.py
- hazelcast/serialization/objects.py
- hazelcast/serialization/service.py
- hazelcast/util.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
We were performing lazy deserialization on APIs that return a list of data, such as map#values(). This was not going to work with Compact, as after returning the list to the user, there might be Compact serialized data on the list which we don't have the schema on the client yet. If it was a normal response, the client would have fetched the schema, but it is not possible with these lazy APIs. We perform the deserialization while getting the list items and this is a sync API. We can't perform a blocking call there, because there is a chance that this will be executed in the reactor thread, which would result in a deadlock.
So, the only possible way of making these APIs work with Compact is to convert them to eager deserialization.
This PR removes lazy deserialization in everything apart …
> Eagerly deserialize responses consisting of list of data [API-1964]

- docs/serialization.rst
- hazelcast/protocol/builtin.py
- hazelcast/protocol/codec/sql_execute_codec.py
- hazelcast/protocol/codec/sql_fetch_codec.py
- hazelcast/serialization/portable/serializer.py
- hazelcast/sql.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
- tests/integration/backward_compatible/sql_test.py
Due to lazy deserialization, Compact serialized objects were
not working nicely with SQL. It was possible to get deserialization
errors that cannot be easily understood by the user.
Similar to what we did for other APIs, we have removed lazy
deserialization from this API as well.
To do that efficiently, I have modified the protocol code generator
so that we can pass to_object function to the SqlPageCodec where
we can do deserialization while filling rows and columns, so that
we will not iterate over the result set once more.
protocol pr: https://github.com/hazelcast/hazelcast-client-protocol/pull/461
> Eagerly deserialize SQL columns of type OBJECT [API-1964]

- README.rst
- docs/getting_started.rst
- examples/README.md
- examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
- examples/paging-predicate/member-with-comparator/pom.xml
- hazelcast/serialization/api.py
- Updated the Hazelcast version used in README and examples to 5.2
- Renamed CompactSerializableClass to CompactSerializableType to be more consistent with the other type-var definitions.
> Introduce minor fixes before 5.2.0

- tests/integration/backward_compatible/proxy/topic_test.py
The codec for publish_all is added to the Hazelcast in version 4.1.
Therefore, we need to add the server check to the backward compatible topic publish_all tests, as we run the client against Hazelcast version 4.0 as well.
> Add server version check to topic publish_all tests

- README.rst
- docs/features.rst
- docs/index.rst
- docs/setting_up_client_network.rst
- examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
- hazelcast/client.py
- hazelcast/discovery.py
We are now defaulting to the Viridian, instead of Cloud, so that our documentation should also reflect that.
Therefore, I have replaced usages of Hazelcast Cloud with Hazelcast Viridian in this PR.
> Use the Viridian name for cloud discovery documentations

- README.rst
- docs/conf.py
- docs/getting_started.rst
- examples/README.md
- examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
- examples/paging-predicate/member-with-comparator/pom.xml
- hazelcast/__init__.py
Also, bumped the version of the Hazelcast in couple of places to 5.3.0.
> Bump client version to 5.3.0

- .github/workflows/update_lets_encrypt_certificate.yml
This PR adds a workflow to update the Let's Encrypt certificate used in tests periodically.
The workflow updates the certificate used in tests every month, based on the certificate generated in the private test artifacts repo. The certificate is renewed every week there, and each certificate is valid for 3 months, so renewing the certificate in this repo every month should work without a problem.
> Update Let's Encrypt certificate periodically

- examples/jupyter-notebooks/Hazelcast Python Client SQL Support with Hazelcast Viridian Notebook.ipynb
Replace any references to `https://docs.hazelcast.com/hazelcast/5.x` with `https://docs.hazelcast.com/hazelcast/latest`
> Update Hazelcast documentation link version

- start_rc.py
The `python run_tests.py` script cannot be run as it has the same problem as described in https://github.com/hazelcast/hazelcast-cpp-client/pull/1206
> Update dependency:get command to latest syntax

- tests/unit/discovery/hazelcast_cloud_discovery_test.py
Python 3.12 ssl no longer has the `ssl.wrap_socket` method but it is replaced with the ssl_context usage. The tests fail at 3.12 build without this fix.
> Python 3.12 ssl no longer has the `ssl.wrap_socket` method causes `hazelcast_cloud_discovery_test` failure [API-2195]

- docs/using_python_client_with_hazelcast.rst
- examples/reliable-topic/reliable_topic_example.py
- hazelcast/proxy/reliable_topic.py
- tests/integration/backward_compatible/proxy/reliable_topic_test.py
Added the new on_cancel callback which is called when the ReliableMessageListener is cancelled for any reason.
Added the documentation, tests and code sample update.
> Added the new on_cancel callback to ReliableMessageListener [API-2195]

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
The `setup-java` [documentation highlights that AdoptOpenJDK no longer receives security updates](https://github.com/actions/setup-java#:~:text=NOTE%3A%20AdoptOpenJDK%20got%20moved%20to%20Eclipse%20Temurin), and instead the Eclipse Temurin JDK should be used.
Fixes [HZ-4195](https://hazelcast.atlassian.net/browse/HZ-4195)
[HZ-4195]: https://hazelcast.atlassian.net/browse/HZ-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Migrate GitHub actions from AdoptOpenJDK to Eclipse Temurin [HZ-4195]

- tests/integration/backward_compatible/proxy/reliable_topic_test.py
Removed the unneeded dependency on `hazelcast.types` so that the backward compatibility tests do not fail.
> Removed the unneeded dependency on `hazelcast.types` in the test

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
- README.rst
- examples/vector_collection/vector_collection.py
- hazelcast/protocol/codec/custom/vector_search_options_codec.py
- hazelcast/protocol/codec/custom/vector_search_result_codec.py
- hazelcast/protocol/codec/vector_collection_clear_codec.py
- hazelcast/protocol/codec/vector_collection_optimize_codec.py
- hazelcast/protocol/codec/vector_collection_put_all_codec.py
- hazelcast/protocol/codec/vector_collection_search_near_vector_codec.py
- hazelcast/protocol/codec/vector_collection_size_codec.py
- hazelcast/proxy/vector_collection.py
- hazelcast/vector.py
- start_rc.py
- tests/integration/backward_compatible/proxy/vector_collection_test.py
Implement client side changes related to recent client protocol changes and some cleanup:
- move vector to top-level search parameter
- add search hints (minimal API with `Dict[str, str]`, can be improved later to be more python-like)
- add `optimize` and `clear`
- add `size`
- fix automatically generated codecs (https://github.com/hazelcast/hazelcast-client-protocol/pull/528)
- additional vector JARs are no longer needed
- add `Document.__repr__` for easier printing
- removed default search limit, `-1` was invalid value
- use V7 license key for tests
> Update vector collection API - search, optimize, clear, size

- Makefile
- hazelcast/util.py
- tests/integration/backward_compatible/proxy/vector_collection_test.py
- tests/integration/backward_compatible/threading_test.py
- tests/unit/proxy/cp/atomic_long_test.py
- tests/unit/proxy/cp/atomic_reference_test.py
Fixed compatibility tests, use current_thread instead of deprecated currentThread.
> Fixed compatibility tests

- .github/workflows/coverage_runner.yml
- README.rst
- hazelcast/proxy/cp/count_down_latch.py
- settings.xml
- start_rc.py
- tests/integration/backward_compatible/proxy/cp/atomic_long_test.py
- tests/integration/backward_compatible/proxy/cp/atomic_reference_test.py
- tests/integration/backward_compatible/proxy/cp/count_down_latch_test.py
- tests/integration/backward_compatible/proxy/cp/fenced_lock_test.py
- tests/integration/backward_compatible/proxy/cp/semaphore_test.py
- tests/integration/backward_compatible/serialization/compact_compatibility/compact_compatibility_test.py
* Updates the artifact downloader to use snapshots from the private repo.
* Mark more CP tests as enterprise
The tests fail since the artifacts cannot be downloaded.
Once the PR is merged, H workflow updates will be in-effect, and the artifacts will be downloaded fine.
> Use the private snapshot repo

- docs/using_python_client_with_hazelcast.rst
The PR builder is failing for unrelated PRs because a link in the documentation is dead.
Fixes: https://github.com/hazelcast/hazelcast-python-client/pull/689#issuecomment-2264537706
> Fix broken entry processor documentation link

- .readthedocs.yaml
The documentation is failing to upload to ReadTheDocs [because it doesn't build](https://app.readthedocs.org/projects/hazelcast/builds/25183105/):
> Config file not found at default path The required .readthedocs.yaml configuration file was not found at repository's root.
This means that the [latest available version](https://hazelcast.readthedocs.io/en/latest/) listed is `v5.3.0`, `v5.4.0` is missing:
I've created a simple configuration [based on their documentation](https://docs.readthedocs.io/en/stable/config-file/index.html) to address this.
I've [built this on ReadTheDocs](https://app.readthedocs.org/projects/hazelcast/builds/25186169/) to create a public-but-unlisted site [here](https://hazelcast.readthedocs.io/en/fix-readthedocs-3/).
Discovered by [PR …
> Fix ReadTheDocs by adding configuration file

- docs/conf.py
The latest `hazelcast-python-client` release is `5.4.0`, but the Sphinx configuration has not been updated so it's still labelled `5.3.0` in the documentation.
Post Merge:
> Upgrade version in documentation

- docs/Makefile
- docs/conf.py
The version specified in the documentation is provided by the Sphinx config in `docs/conf.py`.
This duplicates the version specified in `hazelcast/init.py`, and previously [became outdated](https://github.com/hazelcast/hazelcast-python-client/pull/690).
Unfortunately, in this PR I updated the version incorrectly (i.e. to `5.4.0`, not `5.5.0`), highlighting the issues with duplicating this data.
Instead, we should have a single place the version if specified, and reference it in the Sphinx config.
Example output following this change:
In addition, while trying to build the documents locally, `make html` failed with a cryptic error message:
> *** commands commence before first target. Stop.
I didn't have Sphinx installed, and while `make` was happy to evaluate the `if` check for it's …
> Remove Sphinx version duplication

- .github/workflows/nightly_runner.yml
This PR removes PyPy 3.9 from nightly tests, since Thrift compilaiton fails during pre--test setup , which in turn causes the failure of nightly tests:
https://github.com/hazelcast/hazelcast-python-client/actions/runs/10500661230/job/29089388966
Note that PyPy was never advertised as a supported Python variant. Removal of this test setup doesn't preclude unofficial PyPy support.
> Removed pypy from nightlies

- hazelcast/vector.py
With the update to version 3 of the jVector library, the maxBean parameter now represents the maximum degree of the graph, rather than half of the maximum degree.
see - https://github.com/jbellis/jvector/blob/main/UPGRADING.md?plain=1#L7
> Upgrading JVector version to v.3 [AI-155] [AI-133]

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
Tests cannot be started because `actions/upload-artifact@v2` was deprecated.
Upgrading to `v4`.
The tests in this PR fail, since they run using the v2 action.
> Upgrade actions/upload-artifact so nightly tests can be run

- tests/integration/backward_compatible/proxy/vector_collection_test.py
To fix https://github.com/hazelcast/client-compatibility-suites/actions/runs/11251938480/job/31296205053
> Skip test_backupCount_valid_values_pass if client version is older than 6.0

- hazelcast/protocol/codec/vector_collection_optimize_codec.py
- hazelcast/proxy/vector_collection.py
Add support for [UUID for `optimize` operation](https://github.com/hazelcast/hazelcast-client-protocol/pull/535) which fixes some [optimization operation retry scenarios](https://github.com/hazelcast/hazelcast-mono/pull/3428).
> Send UUID in vector collection optimization request [AI-148]

- hazelcast/__init__.py
- tests/integration/backward_compatible/proxy/vector_collection_test.py
Add tests for setting Vector Collection `backup_count` and `async_backup_count` configuration.
> Add tests for Vector Collection backup config

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail.
I have not tested this change, if problems are reported we can address them as they occur - but we must upgrade to ensure the builds _actually work_.
> Migrate GitHub Actions off of outdate `ubuntu-20.04` runner image

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
In https://github.com/hazelcast/hazelcast-python-client/pull/717 the runner images were upgraded from Ubuntu `20` to Ubuntu `24` (implicit).
[Ubuntu `24` does not have an available Python `3.7` installation](https://github.com/actions/setup-python/issues/962), so the [actions fail](https://github.com/hazelcast/hazelcast-python-client/actions/runs/13270208556).
Changes:
- removed Python `3.7` from GitHub Actions
- upgraded `setup-python` action to latest (while investigating)
> Remove Python `3.7` from GitHub Actions

- .github/workflows/get-python-versions.yml
Addresses https://github.com/hazelcast/hazelcast-python-client/pull/719#pullrequestreview-2622720438.
Will also require updating branch protection rules.
> Add Python `3.13` to GitHub Actions

- .github/workflows/coverage_runner.yml
We restrict actions' execution to members of the `hazelcast` organisation using `hazelcast/hazelcast-tpm/membership`, passing in the user derviced from `github.event.pull_request.head.repo.owner.login`.
This is the owner of the repository, _not_ the user itself.
In the case of a non-fork PR - i.e. one in the `hazelcast` original repo - the `owner` will be `hazelcast` (which _isn't_ a GitHub user, and _isn't_ a member of the `hazelcast` organisation) and will fail.
This nuance prevented https://github.com/hazelcast/hazelcast-python-client/pull/720 from being merged.
Instead we should query `github.actor` as [already used in the C++ client](https://github.com/hazelcast/hazelcast-cpp-client/blame/b63e40748aa8e06f790510d86e1eae87cc36925a/.github/workflows/build-pr.yml#L50).
> Improve GitHub Actions `hazelcast` membership check

- tests/soak_test/README.md
In https://issues.apache.org/jira/browse/MNG-5151 Maven updated the default URL from `repo1.maven.org/maven2` -> `repo.maven.apache.org/maven2`.
Updated references to suit.
> Update Maven central URL

- .github/workflows/coverage_runner.yml
- .github/workflows/nightly_runner.yml
We should try to use a single secrets manager where possible.
[Slack discussion](https://hazelcast.slack.com/archives/CE8GYK5QX/p1754657344019809?thread_ts=1754650773.398089&cid=CE8GYK5QX)
Fixes: [DI-588](https://hazelcast.atlassian.net/browse/DI-588)
[DI-588]: https://hazelcast.atlassian.net/browse/DI-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Get Hazelcast Enteprise License Key from AWS [DI-588]

- docs/getting_started.rst
It seems the following anchor in the Hz docs changed:
https://docs.hazelcast.com/hazelcast/latest/getting-started/install-hazelcast#using-a-package-manager
That causes a failure creating the Python docs.
> [TRIVIAL] Fixed documentation link
